// Canonical recurring-character roster and relationship memory contract.
// Ambient pedestrians may stay modular; recurring NPCs must remember the player,
// hold opinions, change greetings, and own at least one story or service thread.

const freeze = (value) => Object.freeze(value);
const npc = (definition) => freeze({
  recurring: true,
  personality: 'grounded',
  relationshipStages: ['stranger', 'familiar', 'regular', 'trusted', 'close'],
  services: [],
  questIds: [],
  topics: [],
  opinions: {},
  schedule: {},
  ...definition,
  relationshipStages: freeze(definition.relationshipStages || ['stranger', 'familiar', 'regular', 'trusted', 'close']),
  services: freeze(definition.services || []),
  questIds: freeze(definition.questIds || []),
  topics: freeze(definition.topics || []),
  opinions: freeze({ ...(definition.opinions || {}) }),
  schedule: freeze({ ...(definition.schedule || {}) }),
});

export const RELATIONSHIP_THRESHOLDS = freeze({
  stranger: 0,
  familiar: 10,
  regular: 25,
  trusted: 50,
  close: 80,
  rival: -20,
  hostile: -50,
});

export const NPC_STORY_CATALOG = freeze([
  npc({ id: 'coach-rell', name: 'Coach Rell', townId: 'starter-town', districtId: 'parkside-commons', role: 'gym-trainer', personality: 'dry-gruff', services: ['gym-training'], questIds: ['gym-intro', 'coach-rell-no-shortcuts'], topics: ['training', 'discipline', 'parkside', 'player-progress', 'local-rumors'], opinions: { 'officer-dane': 'Respects his patience, hates his parking tickets.', 'maya-brooks': 'Says she could run the gym better than he does. He knows she is probably right.' }, schedule: { morning: 'Iron City Gym floor', afternoon: 'Parkside track', evening: 'Gym office' } }),
  npc({ id: 'maya-brooks', name: 'Maya Brooks', townId: 'starter-town', districtId: 'market-mile', role: 'retail-clerk', personality: 'quick-cheery', services: ['kicks-and-fits-shop'], questIds: ['maya-missed-order'], topics: ['fashion', 'market-mile', 'deliveries', 'work-drama', 'player-style'], opinions: { 'coach-rell': 'Needs better music in the gym.', 'malik-frost': 'Good taste, terrible sense of time.' }, schedule: { morning: 'Kicks & Fits stockroom', afternoon: 'Kicks & Fits counter', evening: 'Market Mile vendor row' } }),
  npc({ id: 'officer-dane', name: 'Officer Dane', townId: 'starter-town', districtId: 'civic-heights', role: 'police-officer', personality: 'calm-wry', services: ['police-desk', 'academy-information'], questIds: ['police-orientation', 'dreamdrop-police-applicant', 'clean-up-your-name'], topics: ['law', 'police-career', 'records', 'school-zone', 'community-safety'], opinions: { 'denise-hall': 'The city would collapse in four days without sanitation.', 'coach-rell': 'Good with kids. Loud with everybody.' }, schedule: { morning: 'Scholar Road crossing detail', afternoon: 'Dreamdrop Public Safety', evening: 'Civic Heights patrol' } }),
  npc({ id: 'denise-hall', name: 'Denise Hall', townId: 'starter-town', districtId: 'market-mile', role: 'sanitation-lead', personality: 'practical-sharp', services: ['sanitation-jobs'], questIds: ['cleanup-crew', 'sanitation-routes'], topics: ['cleanup-routes', 'city-services', 'illegal-dumping', 'worktower', 'neighborhood-pride'], opinions: { 'officer-dane': 'Helpful when he listens before writing.', 'maya-brooks': 'Always gives the crew cold water.' }, schedule: { morning: 'Sanitation route', afternoon: 'Market Mile dumpster station', evening: 'WorkTower service counter' } }),
  npc({ id: 'malik-frost', name: 'Malik Frost', townId: 'starter-town', districtId: 'dreamdrop-district', role: 'jeweler', personality: 'smooth-observant', services: ['frostbox-shop', 'custom-chain-builder'], questIds: ['frostbox-first-look', 'custom-made-name'], topics: ['jewelry', 'custom-orders', 'city-gems', 'market-trust', 'player-style'], opinions: { 'maya-brooks': 'Can sell a plain hoodie like it is a limited release.', 'officer-dane': 'Not invited behind the counter.' }, schedule: { morning: 'Frostbox workshop', afternoon: 'Frostbox showroom', evening: 'Dreamdrop café table' } }),
  npc({ id: 'ms-janice', name: 'Ms. Janice', townId: 'starter-town', districtId: 'willowbend-residential', role: 'neighbor', personality: 'warm-nosy', services: [], questIds: ['willowbend-neighbor'], topics: ['willowbend', 'old-dreamdrop', 'neighbors', 'home-upgrades', 'who-came-home-late'], opinions: { 'officer-dane': 'A good boy who needs to call his auntie.', 'denise-hall': 'The only person who knows what day bulk pickup actually comes.' }, schedule: { morning: 'Front porch', afternoon: 'Community garden', evening: 'Living room window' } }),
  npc({ id: 'cap-odell', name: 'Cap Odell', townId: 'fishing-harbor', districtId: 'harbor-center', role: 'harbor-master', personality: 'weathered-gruff', services: ['permits', 'boat-rental'], questIds: ['arrival-fishing-harbor', 'fish-stories', 'something-changed'], topics: ['tides', 'permits', 'gillyfish', 'lighthouse', 'protected-water'], opinions: { 'sela-voss': 'Would sell fog if she could bottle it.', 'dr-nia-current': 'Smart enough to make him admit when he is wrong.' }, schedule: { dawn: 'Harbor Master dock', morning: 'Permit desk', afternoon: 'Patrol pier', evening: 'Dockside Diner' } }),
  npc({ id: 'sela-voss', name: 'Sela Voss', townId: 'fishing-harbor', districtId: 'market-wharf', role: 'market-vendor', personality: 'bargaining-bright', services: ['seafood-market'], questIds: ['harbor-honest-work'], topics: ['fish-prices', 'market-rumors', 'rare-catches', 'tourists', 'storms'], opinions: { 'cap-odell': 'Charges for permits, complains when she charges for fish.', 'harbor-patrol': 'Useful until they inspect the freezer.' }, schedule: { dawn: 'Fish auction', morning: 'Seafood counter', afternoon: 'Market office', evening: 'Boardwalk stall' } }),
  npc({ id: 'dr-nia-current', name: 'Dr. Nia Current', townId: 'fishing-harbor', districtId: 'marine-academy', role: 'marine-scientist', personality: 'curious-direct', services: ['marine-certification'], questIds: ['permit-to-go-deep', 'lighthouse-static'], topics: ['marine-ecology', 'sonar', 'gillyfish', 'adaptation', 'aqualume-theories'], opinions: { 'cap-odell': 'Pretends every discovery was obvious after it is discovered.', 'current-guard': 'A rumor with paperwork, until proven otherwise.' }, schedule: { morning: 'Academy lab', afternoon: 'Lighthouse field station', evening: 'Specimen archive' } }),
  npc({ id: 'celeste-crown', name: 'Celeste Crown', townId: 'rich-hills', districtId: 'luxury-row', role: 'property-broker', personality: 'polished-candid', services: ['property-office'], questIds: ['arrival-rich-hills', 'work-your-way-in'], topics: ['property', 'negotiation', 'estate-ridge', 'worker-housing', 'status'], opinions: { 'marcus-vale': 'Excellent security chief. Terrible at parties.', 'priya-shah': 'Could automate half the town and offend the other half.' }, schedule: { morning: 'Golden Key Realty', afternoon: 'Property tours', evening: 'Garden Commons events' } }),
  npc({ id: 'marcus-vale', name: 'Marcus Vale', townId: 'rich-hills', districtId: 'estate-ridge', role: 'security-chief', personality: 'formal-fair', services: ['security-clearance'], questIds: [], topics: ['gates', 'trespass', 'estate-safety', 'security-career', 'second-chances'], opinions: { 'celeste-crown': 'Understands boundaries better than most owners.', 'officer-dane': 'Would hire him tomorrow.' }, schedule: { morning: 'Grand Entry', afternoon: 'Estate Ridge patrol', evening: 'Security office' } }),
  npc({ id: 'priya-shah', name: 'Priya Shah', townId: 'tech-city', districtId: 'neon-core', role: 'systems-founder', personality: 'fast-optimistic', services: ['coding-contracts', 'gridlink-support'], questIds: ['signal-in-the-crowd', 'gridlink-dead-zone', 'wrong-address'], topics: ['gridlink', 'startups', 'debugging', 'surveillance', 'tech-ethics'], opinions: { 'marcus-vale': 'Thinks every bug is a trespasser.', 'cap-odell': 'Still writes tide notes on paper. Respectfully unhinged.' }, schedule: { morning: 'CodeNest', afternoon: 'Gadget Forge', evening: 'GridLine Transit Hub' } }),
  npc({ id: 'jax-byte', name: 'Jax Byte', townId: 'tech-city', districtId: 'innovation-strip', role: 'gadget-technician', personality: 'cool-skeptical', services: ['gadget-repair', 'drone-parts'], questIds: [], topics: ['repairs', 'black-market-tech', 'drones', 'gridlink-casings', 'corporate-security'], opinions: { 'priya-shah': 'Builds the future and forgets to eat lunch.', 'metro-security': 'Great cameras. Bad sense of humor.' }, schedule: { morning: 'Gadget Forge bench', afternoon: 'Innovation Strip', evening: 'Utility Edge food truck' } }),
  npc({ id: 'vincent-luck', name: 'Vincent Luck', townId: 'casino-strip', districtId: 'neon-plaza', role: 'game-hall-dealer', personality: 'silky-honest', services: ['blackjack', 'roulette'], questIds: ['arrival-casino-strip'], topics: ['odds', 'house-rules', 'regulars', 'security', 'knowing-when-to-stop'], opinions: { 'nora-bright': 'Runs the hotel like the sun owes her rent.', 'lana-starr': 'Always performing, even in elevators.' }, schedule: { afternoon: 'Training tables', evening: 'Grand Chance floor', late: 'Neon Plaza café' } }),
  npc({ id: 'nora-bright', name: 'Nora Bright', townId: 'casino-strip', districtId: 'grand-hotel-row', role: 'hotel-manager', personality: 'high-energy-exacting', services: ['hotel-jobs', 'room-service'], questIds: [], topics: ['hospitality', 'guest-drama', 'hotel-events', 'worker-housing', 'starline-visitors'], opinions: { 'vincent-luck': 'The only dealer who tells guests to go to bed.', 'lana-starr': 'Checks in under fake names nobody believes.' }, schedule: { morning: 'Hotel service floors', afternoon: 'Grand Aurora lobby', evening: 'Event ballroom' } }),
  npc({ id: 'elder-wyn', name: 'Elder Wyn', townId: 'dungeon-outskirts', districtId: 'outpost-commons', role: 'guild-elder', personality: 'gentle-serious', services: ['quest-board'], questIds: ['arrival-dungeon-outskirts'], topics: ['dungeon-floors', 'relics', 'return-rules', 'guild-history', 'fear'], opinions: { 'borin-ironroot': 'Complains because optimism does not hold an edge.', 'warden-akeem': 'Trusts rules because he has seen what happens without them.' }, schedule: { morning: 'Guild archive', afternoon: 'Outpost Commons', evening: 'Shrine Court' } }),
  npc({ id: 'borin-ironroot', name: 'Borin Ironroot', townId: 'dungeon-outskirts', districtId: 'forge-row', role: 'blacksmith', personality: 'blunt-loyal', services: ['weapon-upgrades', 'gear-repair'], questIds: [], topics: ['crafting', 'materials', 'bad-gear', 'good-tools', 'dungeon-rumors'], opinions: { 'elder-wyn': 'Too many words. Usually right.', 'warden-akeem': 'Returns borrowed tools cleaner than he found them.' }, schedule: { morning: 'Forge', afternoon: 'Forge', evening: 'Still the forge' } }),
  npc({ id: 'warden-akeem', name: 'Warden Akeem', townId: 'dungeon-outskirts', districtId: 'warden-watch', role: 'warden', personality: 'measured-protective', services: ['permits', 'illegal-relic-turn-in'], questIds: [], topics: ['sealed-floors', 'rescue', 'illegal-relics', 'warden-career', 'reform'], opinions: { 'elder-wyn': 'Sees possibilities. He sees casualty reports.', 'borin-ironroot': 'Pretends he does not donate gear to beginners.' }, schedule: { morning: 'Warden Station', afternoon: 'Gate approach', evening: 'Watchtower' } }),
  npc({ id: 'coach-tavi', name: 'Coach Tavi', townId: 'obby-canyon', districtId: 'momentum-academy', role: 'movement-coach', personality: 'competitive-kind', services: ['movement-training'], questIds: ['arrival-obby-canyon'], topics: ['courses', 'failure', 'route-memory', 'rivals', 'course-design'], opinions: { 'ranger-sol': 'Can spot a loose bolt from across the canyon.', 'coach-rell': 'Would turn every course into leg day.' }, schedule: { morning: 'Beginner Valley', afternoon: 'Momentum Academy', evening: 'Course Select Plaza' } }),
  npc({ id: 'ranger-sol', name: 'Ranger Sol', townId: 'obby-canyon', districtId: 'ranger-rescue', role: 'canyon-ranger', personality: 'alert-deadpan', services: ['course-safety', 'rescue-jobs'], questIds: [], topics: ['safety', 'course-sabotage', 'rescue', 'wind', 'shortcuts'], opinions: { 'coach-tavi': 'Encouraging enough to be dangerous. Competent enough to get away with it.' }, schedule: { morning: 'Checkpoint controls', afternoon: 'Course patrol', evening: 'Ranger Station' } }),
  npc({ id: 'lana-starr', name: 'Lana Starr', townId: 'starline-city', districtId: 'premiere-boulevard', role: 'talent-agent', personality: 'cool-demanding', services: ['auditions', 'talent-representation'], questIds: ['arrival-starline-city'], topics: ['auditions', 'reputation', 'branding', 'backlot-politics', 'career-recovery'], opinions: { 'nora-bright': 'Could manage a live dragon and still upsell the suite.', 'vincent-luck': 'Wastes a perfect stage voice announcing cards.' }, schedule: { morning: 'Talent Agency', afternoon: 'Studio meetings', evening: 'Premiere events' } }),
  npc({ id: 'devon-cue', name: 'Devon Cue', townId: 'starline-city', districtId: 'backlot', role: 'stage-manager', personality: 'tired-funny', services: ['stagehand-jobs'], questIds: [], topics: ['production', 'props', 'actors', 'set-safety', 'what-went-wrong-today'], opinions: { 'lana-starr': 'Can schedule a miracle but not a lunch break.', 'nora-bright': 'The only person who labels cables better than he does.' }, schedule: { morning: 'Sound Stage A', afternoon: 'Backlot loop', evening: 'Encore Music Hall' } }),
  npc({ id: 'captain-lyra-current', name: 'Captain Lyra Current', townId: 'aqualume', districtId: 'civic-crown', role: 'current-guard-captain', personality: 'formal-warm', services: ['current-guard', 'fines', 'rescue'], questIds: ['crown-of-the-deep', 'visitor-or-resident', 'under-new-pressure'], topics: ['aqualume-law', 'surface-visitors', 'salvage', 'sanctuary', 'abyss-rescue'], opinions: { 'dr-nia-current': 'A surface scientist who asked the right questions.', 'cap-odell': 'Has been arguing with the sea longer than she has been alive.' }, schedule: { morning: 'Moonpool Gateway', afternoon: 'Current Guard Precinct', evening: 'Lumen Plaza patrol' } }),
  npc({ id: 'orin-pearl', name: 'Orin Pearl', townId: 'aqualume', districtId: 'coral-market', role: 'salvage-appraiser', personality: 'patient-shrewd', services: ['salvage-exchange', 'pearl-appraisal'], questIds: [], topics: ['salvage', 'surface-goods', 'gillyfish', 'illegal-relics', 'market-prices'], opinions: { 'captain-lyra-current': 'Knows every law. He knows every exception worth requesting.', 'priya-shah': 'Would put a screen on a seashell.' }, schedule: { morning: 'Pearl Exchange', afternoon: 'Coral Market', evening: 'Reefside community kitchen' } }),
  npc({ id: 'miri-kelp', name: 'Miri Kelp', townId: 'aqualume', districtId: 'sanctuary-gardens', role: 'sanctuary-caretaker', personality: 'soft-firm', services: ['sea-life-care', 'sanctuary-tours'], questIds: [], topics: ['sea-life', 'coral', 'surface-pollution', 'creature-signals', 'protected-zones'], opinions: { 'captain-lyra-current': 'Understands that rescue is part of law.', 'orin-pearl': 'Appraises everything except his own bad jokes.' }, schedule: { morning: 'Coral nursery', afternoon: 'Sanctuary Gardens', evening: 'Creature clinic' } }),
]);

export const NPCS_BY_ID = freeze(Object.fromEntries(NPC_STORY_CATALOG.map((entry) => [entry.id, entry])));

export function relationshipStage(score = 0) {
  if (score <= RELATIONSHIP_THRESHOLDS.hostile) return 'hostile';
  if (score <= RELATIONSHIP_THRESHOLDS.rival) return 'rival';
  if (score >= RELATIONSHIP_THRESHOLDS.close) return 'close';
  if (score >= RELATIONSHIP_THRESHOLDS.trusted) return 'trusted';
  if (score >= RELATIONSHIP_THRESHOLDS.regular) return 'regular';
  if (score >= RELATIONSHIP_THRESHOLDS.familiar) return 'familiar';
  return 'stranger';
}

export default NPC_STORY_CATALOG;
