// ───────────────────────────────────────────────────────────────────────────
// questCatalog.js — canonical authored quest/story data for Zaylins.
//
// Runtime-ready quests use gameplay events already emitted by main.js. Planned
// quests reserve future story, choice, travel, school, career, and town hooks so
// implementation agents do not invent incompatible progression later.
// ───────────────────────────────────────────────────────────────────────────

const freeze = (value) => Object.freeze(value);

export const QUEST_CATEGORIES = freeze({
  story: { label: 'Story', icon: '★' },
  town: { label: 'Town', icon: '⌂' },
  people: { label: 'People', icon: '☺' },
  career: { label: 'Career', icon: '▣' },
  activities: { label: 'Activities', icon: '◆' },
});

export const QUEST_IMPLEMENTATION = freeze({
  runtime: 'runtime',
  planned: 'planned',
});

const objective = (id, text, event, options = {}) => freeze({
  id,
  text,
  event,
  arg: options.arg,
  count: Math.max(1, options.count || 1),
  optional: !!options.optional,
});

const quest = (definition) => freeze({
  category: 'town',
  townId: 'starter-town',
  implementation: QUEST_IMPLEMENTATION.planned,
  autoStart: false,
  repeatable: false,
  secret: false,
  ordered: false,
  completionMode: 'all',
  prerequisites: [],
  unlocks: [],
  consequenceRefs: [],
  objectives: [],
  rewards: {},
  ...definition,
  prerequisites: freeze([...(definition.prerequisites || [])]),
  unlocks: freeze([...(definition.unlocks || [])]),
  consequenceRefs: freeze([...(definition.consequenceRefs || [])]),
  objectives: freeze([...(definition.objectives || [])]),
  rewards: freeze({ ...(definition.rewards || {}) }),
});

export const QUEST_CATALOG = freeze([
  quest({
    id: 'welcome-to-dreamdrop',
    title: 'Welcome to Dreamdrop',
    summary: 'Get your bearings and meet somebody who knows the block.',
    category: 'story',
    implementation: 'runtime',
    autoStart: true,
    trackedByDefault: true,
    ordered: true,
    objectives: [objective('meet-the-block', 'Talk to someone on the street', 'talk-city')],
    rewards: { money: 150, stats: { fun: 10 }, flags: ['arrived-in-dreamdrop'] },
    unlocks: ['first-day-your-way'],
  }),
  quest({
    id: 'first-day-your-way',
    title: 'First Day, Your Way',
    summary: 'Start building a life. Study, work, or help the neighborhood first.',
    category: 'story',
    implementation: 'runtime',
    autoStart: true,
    trackedByDefault: true,
    completionMode: 'any',
    prerequisites: ['welcome-to-dreamdrop'],
    objectives: [
      objective('choose-school', 'Complete a study session at Zaylins Prep', 'study-done'),
      objective('choose-work', 'Complete any paid shift', 'job-done'),
      objective('choose-community', 'Finish a sanitation cleanup quota', 'trash-done'),
    ],
    rewards: { money: 200, flags: ['first-day-complete'] },
    unlocks: [
      'chicken-run', 'frostbox-first-look', 'home-base', 'gym-intro',
      'school-intro', 'first-job', 'cleanup-crew', 'dealership-tour',
      'snack-stop', 'police-orientation', 'gem-hunter', 'daily-life',
    ],
  }),
  quest({
    id: 'chicken-run',
    title: 'Chicken Run',
    summary: 'Learn food, shopping, conversation, and hunger recovery at Chicken Spot.',
    category: 'town',
    implementation: 'runtime',
    ordered: true,
    prerequisites: ['first-day-your-way'],
    objectives: [
      objective('enter-chicken', 'Enter Chicken Spot', 'enter', { arg: 'chicken' }),
      objective('meet-cashier', 'Talk to the cashier', 'talk-int', { arg: 'cashier' }),
      objective('buy-chicken', 'Buy a piece of chicken', 'buy-chicken'),
      objective('eat-chicken', 'Eat it clean to the bone', 'eat-done'),
    ],
    rewards: { money: 120, stats: { hunger: 20 }, flags: ['knows-food-loop'] },
    unlocks: ['maya-missed-order'],
  }),
  quest({
    id: 'frostbox-first-look',
    title: 'Frostbox First Look',
    summary: 'Meet the jeweler, browse the ice, and bring in a city gem.',
    category: 'town',
    implementation: 'runtime',
    ordered: false,
    prerequisites: ['first-day-your-way'],
    objectives: [
      objective('enter-frostbox', 'Enter Frostbox', 'enter', { arg: 'frostbox' }),
      objective('meet-jeweler', 'Talk to the jeweler', 'talk-int', { arg: 'jeweler' }),
      objective('collect-gem', 'Collect a gem in the city', 'gem'),
    ],
    rewards: { money: 200, stats: { fun: 8 }, flags: ['met-frostbox-jeweler'] },
    unlocks: ['custom-made-name'],
  }),
  quest({
    id: 'home-base',
    title: 'Home Base',
    summary: 'Visit Zaylins Home and learn where rest, storage, grooming, and wardrobe live.',
    category: 'story',
    implementation: 'runtime',
    ordered: true,
    prerequisites: ['first-day-your-way'],
    objectives: [objective('enter-home', 'Head home', 'enter', { arg: 'home' })],
    rewards: { money: 60, flags: ['home-tutorial-complete'] },
    unlocks: ['home-haircut', 'willowbend-neighbor'],
  }),
  quest({
    id: 'home-haircut',
    title: 'Fresh Start',
    summary: 'Use the clippers at home and finish a lineup.',
    category: 'activities',
    implementation: 'runtime',
    prerequisites: ['home-base'],
    objectives: [objective('haircut', 'Complete the haircut minigame', 'haircut-done')],
    rewards: { money: 80, stats: { fun: 12, hygiene: 10 }, flags: ['first-fresh-cut'] },
  }),
  quest({
    id: 'gym-intro',
    title: 'Gym Intro',
    summary: 'Put in your first real session at Iron City Gym.',
    category: 'activities',
    implementation: 'runtime',
    ordered: true,
    prerequisites: ['first-day-your-way'],
    objectives: [
      objective('enter-gym', 'Enter Iron City Gym', 'enter', { arg: 'gym' }),
      objective('workout', 'Complete a workout', 'workout-done'),
    ],
    rewards: { money: 90, stats: { fitness: 15 }, flags: ['gym-member-intro'] },
    unlocks: ['coach-rell-no-shortcuts'],
  }),
  quest({
    id: 'school-intro',
    title: 'School Intro',
    summary: 'Attend Zaylins Prep and finish a study session.',
    category: 'career',
    implementation: 'runtime',
    ordered: true,
    prerequisites: ['first-day-your-way'],
    objectives: [
      objective('enter-school', 'Enter Zaylins Prep', 'enter', { arg: 'school' }),
      objective('study', 'Complete a study session', 'study-done'),
    ],
    rewards: { money: 90, stats: { smarts: 15 }, flags: ['school-orientation-complete'] },
    unlocks: ['scholars-quarter-reputation'],
  }),
  quest({
    id: 'first-job',
    title: 'First Paycheck',
    summary: 'Clock in at WorkTower and complete a full shift.',
    category: 'career',
    implementation: 'runtime',
    ordered: true,
    prerequisites: ['first-day-your-way'],
    objectives: [
      objective('enter-office', 'Enter WorkTower', 'enter', { arg: 'office' }),
      objective('finish-shift', 'Work a full shift', 'job-done'),
    ],
    rewards: { money: 250, stats: { fun: 5 }, flags: ['earned-first-paycheck'] },
    unlocks: ['worktower-three-shift-test', 'property-desk-introduction'],
  }),
  quest({
    id: 'cleanup-crew',
    title: 'Cleanup Crew',
    summary: 'Meet sanitation, accept a quota, and leave the block cleaner.',
    category: 'career',
    implementation: 'runtime',
    ordered: true,
    prerequisites: ['first-day-your-way'],
    objectives: [
      objective('talk-sanitation', 'Talk to the sanitation worker', 'talk-sanitation'),
      objective('finish-cleanup', 'Finish a trash cleanup quota', 'trash-done'),
    ],
    rewards: { money: 120, stats: { hygiene: 8 }, flags: ['sanitation-intro-complete'] },
    unlocks: ['sanitation-routes'],
  }),
  quest({
    id: 'dealership-tour',
    title: 'Dealership Tour',
    summary: 'Meet Auto Haus, inspect the floor, and get behind the wheel.',
    category: 'town',
    implementation: 'runtime',
    ordered: true,
    prerequisites: ['first-day-your-way'],
    objectives: [
      objective('enter-dealership', 'Enter Auto Haus', 'enter', { arg: 'dealership' }),
      objective('meet-dealer', 'Talk to the salesperson', 'talk-int', { arg: 'dealer' }),
      objective('enter-ride', 'Get in a vehicle', 'enter-car'),
    ],
    rewards: { money: 100, stats: { fun: 6 }, flags: ['vehicle-intro-complete'] },
    unlocks: ['get-around-town'],
  }),
  quest({
    id: 'get-around-town',
    title: 'Get Around Town',
    summary: 'Take a real drive, learn the roads, then park and step out.',
    category: 'story',
    implementation: 'runtime',
    autoStart: true,
    trackedByDefault: true,
    ordered: true,
    prerequisites: ['dealership-tour'],
    objectives: [
      objective('drive-distance', 'Drive far enough to learn the route', 'drive-checkpoint'),
      objective('park-exit', 'Park and hop out', 'exit-car'),
    ],
    rewards: { money: 130, stats: { fun: 6 }, flags: ['basic-driving-complete'] },
    unlocks: ['keys-to-the-city', 'open-roads'],
  }),
  quest({
    id: 'snack-stop',
    title: 'Snack Stop',
    summary: 'Learn the quick recovery loop at 6twelve.',
    category: 'activities',
    implementation: 'runtime',
    prerequisites: ['first-day-your-way'],
    objectives: [
      objective('buy-snack', 'Buy a snack', 'buy-snack'),
      objective('buy-drink', 'Buy a drink', 'buy-drink'),
    ],
    rewards: { money: 40, stats: { energy: 5, fun: 4 }, flags: ['knows-convenience-loop'] },
  }),
  quest({
    id: 'police-orientation',
    title: 'Know the Law',
    summary: 'Visit Dreamdrop Public Safety before deciding how close to the line you want to live.',
    category: 'career',
    implementation: 'runtime',
    ordered: false,
    prerequisites: ['first-day-your-way'],
    objectives: [
      objective('front-desk', 'Talk to the police front desk', 'talk-police-desk'),
      objective('holding-cells', 'Inspect the holding-cell block', 'police-cells'),
    ],
    rewards: { money: 75, flags: ['law-orientation-complete'] },
    unlocks: ['dreamdrop-police-applicant', 'street-trouble', 'risky-choice'],
  }),
  quest({
    id: 'gem-hunter',
    title: 'Sidewalk Sparkle',
    summary: 'Collect five gems while learning the city on foot.',
    category: 'activities',
    implementation: 'runtime',
    prerequisites: ['first-day-your-way'],
    objectives: [objective('five-gems', 'Collect 5 city gems', 'gem', { count: 5 })],
    rewards: { money: 250, stats: { fun: 10 }, flags: ['gem-hunter-one'] },
  }),
  quest({
    id: 'daily-life',
    title: 'Handle Your Business',
    summary: 'Take care of food, energy, and grooming in one ordinary day.',
    category: 'activities',
    implementation: 'runtime',
    prerequisites: ['first-day-your-way'],
    objectives: [
      objective('daily-snack', 'Buy a snack', 'buy-snack'),
      objective('daily-drink', 'Buy a drink', 'buy-drink'),
      objective('daily-cut', 'Get a fresh lineup', 'haircut-done'),
    ],
    rewards: { money: 180, stats: { hygiene: 5, fun: 5 }, flags: ['daily-life-complete'] },
  }),
  quest({
    id: 'worktower-three-shift-test',
    title: 'Show Up Three Times',
    summary: 'Consistency talks louder than one lucky shift.',
    category: 'career',
    implementation: 'runtime',
    prerequisites: ['first-job'],
    objectives: [objective('three-shifts', 'Complete 3 paid shifts', 'job-done', { count: 3 })],
    rewards: { money: 500, stats: { smarts: 4 }, flags: ['reliable-worker'] },
  }),
  quest({
    id: 'well-rounded',
    title: 'A Little of Everything',
    summary: 'Study, train, and explore instead of becoming one-note.',
    category: 'activities',
    implementation: 'runtime',
    prerequisites: ['gym-intro', 'school-intro'],
    objectives: [
      objective('round-study', 'Complete a study session', 'study-done'),
      objective('round-train', 'Complete a workout', 'workout-done'),
      objective('round-gem', 'Collect a city gem', 'gem'),
    ],
    rewards: { money: 300, stats: { fitness: 5, smarts: 5, fun: 5 }, flags: ['well-rounded-one'] },
  }),
  quest({
    id: 'street-trouble',
    title: 'Street Trouble',
    summary: 'An optional rough route. Stand your ground, walk away, or leave this quest untouched.',
    category: 'town',
    implementation: 'runtime',
    prerequisites: ['police-orientation'],
    objectives: [objective('land-hit', 'Land a hit in a street fight', 'fight')],
    rewards: { money: 60, stats: { fitness: 8 }, flags: ['chose-street-fight'] },
    consequenceRefs: ['street-force-response'],
  }),
  quest({
    id: 'risky-choice',
    title: 'Risky Choice',
    summary: 'Quick cash, real heat, and permanent consequences if the law catches up.',
    category: 'town',
    implementation: 'runtime',
    prerequisites: ['police-orientation'],
    objectives: [objective('rob-civilian', 'Rob a civilian for quick cash', 'rob-done')],
    rewards: { money: 100, stats: { fun: 4 }, flags: ['chose-risk-path'] },
    unlocks: ['police-alert'],
    consequenceRefs: ['starter-crime-record', 'dreamdrop-police-career-bar'],
  }),
  quest({
    id: 'police-alert',
    title: 'Police Alert',
    summary: 'You chose the heat. Lose the pursuit and live with what happened next.',
    category: 'story',
    implementation: 'runtime',
    autoStart: true,
    trackedByDefault: true,
    prerequisites: ['risky-choice'],
    objectives: [objective('lose-cops', 'Lose the police', 'lost-cops')],
    rewards: { money: 150, stats: { fun: 6 }, flags: ['escaped-first-pursuit'] },
    unlocks: ['clean-up-your-name'],
  }),
  quest({
    id: 'clean-up-your-name',
    title: 'Clean Up Your Name',
    summary: 'Visit the station after the chase and learn the difference between heat, charges, and a record.',
    category: 'story',
    implementation: 'runtime',
    prerequisites: ['police-alert'],
    objectives: [objective('return-police', 'Talk to the police front desk', 'talk-police-desk')],
    rewards: { money: 0, flags: ['crime-consequence-explained'] },
  }),

  quest({
    id: 'keys-to-the-city', title: 'Keys to the City', category: 'story',
    summary: 'Complete the full road test, learn repair and fuel, and secure a legal starter vehicle.',
    prerequisites: ['get-around-town'],
    objectives: [
      objective('road-test', 'Pass the marked road test', 'road-test-complete'),
      objective('repair-lesson', 'Complete a garage inspection', 'garage-inspection-complete'),
      objective('fuel-lesson', 'Refuel at 6twelve', 'refuel-complete'),
    ],
    rewards: { money: 500, items: ['starter-vehicle-title'], flags: ['licensed-driver'] },
  }),
  quest({
    id: 'open-roads', title: 'Open Roads', category: 'story',
    summary: 'Reach the Fishing Highway and Eastgate Parkway so the wider world stops being a rumor.',
    prerequisites: ['get-around-town'],
    objectives: [
      objective('north-gateway', 'Reach the Fishing Highway gateway', 'reach-location', { arg: 'st-north-hwy' }),
      objective('east-gateway', 'Reach the Rich Hills Parkway gateway', 'reach-location', { arg: 'st-east-parkway' }),
    ],
    rewards: { money: 250, flags: ['intertown-routes-introduced'] },
    unlocks: ['arrival-fishing-harbor', 'arrival-rich-hills'],
  }),
  quest({
    id: 'maya-missed-order', title: 'Maya’s Missed Order', category: 'people', giverId: 'maya-brooks',
    summary: 'A routine food order turns into a delivery, a misunderstanding, and a choice about taking credit.',
    prerequisites: ['chicken-run'], consequenceRefs: ['maya-credit-choice'],
    objectives: [
      objective('collect-order', 'Collect Maya’s replacement order', 'collect-item', { arg: 'maya-order' }),
      objective('deliver-order', 'Deliver the order to Kicks & Fits', 'deliver-item', { arg: 'maya-order' }),
      objective('resolve-credit', 'Decide who gets credit for fixing the mistake', 'story-choice', { arg: 'maya-credit' }),
    ],
    rewards: { money: 225, reputation: { 'starter-town': 1 }, relationship: { 'maya-brooks': 8 } },
  }),
  quest({
    id: 'custom-made-name', title: 'Custom Made Name', category: 'people', giverId: 'malik-frost',
    summary: 'Help Frostbox trace a lost custom order before somebody sells it twice.',
    prerequisites: ['frostbox-first-look'], consequenceRefs: ['frostbox-lost-chain'],
    objectives: [
      objective('ask-market', 'Question vendors on Market Mile', 'talk-topic', { arg: 'lost-chain' }),
      objective('find-chain', 'Recover the custom chain', 'collect-item', { arg: 'lost-custom-chain' }),
      objective('return-or-sell', 'Return, expose, or secretly sell the chain', 'story-choice', { arg: 'lost-chain-outcome' }),
    ],
    rewards: { money: 600, items: ['frostbox-custom-discount'] },
  }),
  quest({
    id: 'willowbend-neighbor', title: 'The Porch Light', category: 'people', giverId: 'ms-janice',
    summary: 'A neighbor’s porch light keeps cutting out, but the wiring problem is not the whole story.',
    prerequisites: ['home-base'],
    objectives: [
      objective('inspect-porch', 'Inspect the porch light', 'inspect-object', { arg: 'janice-porch-light' }),
      objective('find-breaker', 'Find the tripped alley breaker', 'reach-location', { arg: 'willowbend-breaker' }),
      objective('check-neighbor', 'Return and check on Ms. Janice', 'talk-topic', { arg: 'porch-fixed' }),
    ],
    rewards: { money: 180, relationship: { 'ms-janice': 10 }, flags: ['willowbend-neighbor-known'] },
  }),
  quest({
    id: 'coach-rell-no-shortcuts', title: 'No Shortcuts', category: 'people', giverId: 'coach-rell',
    summary: 'Coach Rell tests whether you want progress or only the appearance of progress.',
    prerequisites: ['gym-intro'], consequenceRefs: ['coach-rell-discipline-choice'],
    objectives: [
      objective('three-workouts', 'Finish 3 workouts without quitting', 'workout-done', { count: 3 }),
      objective('help-newcomer', 'Help a new gym member finish a set', 'assist-npc', { arg: 'gym-newcomer' }),
    ],
    rewards: { money: 350, stats: { fitness: 8 }, relationship: { 'coach-rell': 12 } },
  }),
  quest({
    id: 'scholars-quarter-reputation', title: 'Known in the Hallways', category: 'career',
    summary: 'Build a school reputation through attendance, tutoring, or a club contribution.',
    prerequisites: ['school-intro'], completionMode: 'any',
    objectives: [
      objective('attendance', 'Attend 3 class sessions', 'study-done', { count: 3 }),
      objective('tutor', 'Complete a tutoring session', 'school-job-complete', { arg: 'tutor' }),
      objective('club', 'Help a school club complete an event', 'school-event-complete'),
    ],
    rewards: { money: 300, reputation: { 'zaylins-prep': 2 }, flags: ['school-reputation-one'] },
  }),
  quest({
    id: 'property-desk-introduction', title: 'A Place With Your Name On It', category: 'career',
    summary: 'Meet the WorkTower property desk and learn the difference between renting, owning, and upgrading.',
    prerequisites: ['first-job'],
    objectives: [
      objective('property-desk', 'Talk to the property desk', 'talk-int', { arg: 'property-desk' }),
      objective('inspect-listing', 'Inspect a Willowbend listing', 'inspect-property', { arg: 'starter-listing' }),
    ],
    rewards: { money: 100, flags: ['property-market-unlocked'] },
  }),
  quest({
    id: 'sanitation-routes', title: 'Routes Nobody Notices', category: 'people', giverId: 'denise-hall',
    summary: 'Learn why the city’s “simple” cleanup route keeps failing in the same three places.',
    prerequisites: ['cleanup-crew'],
    objectives: [
      objective('market-clean', 'Complete a Market Mile cleanup', 'trash-route-complete', { arg: 'market-mile' }),
      objective('park-clean', 'Complete a Parkside cleanup', 'trash-route-complete', { arg: 'parkside' }),
      objective('alley-source', 'Find who keeps dumping behind WorkTower', 'discover-clue', { arg: 'illegal-dumping' }),
    ],
    rewards: { money: 450, relationship: { 'denise-hall': 10 }, flags: ['sanitation-route-two'] },
  }),
  quest({
    id: 'dreamdrop-police-applicant', title: 'The Application', category: 'career', giverId: 'officer-dane',
    summary: 'Begin the clean-record police path, or learn exactly why the local department will not take you.',
    prerequisites: ['police-orientation'], consequenceRefs: ['dreamdrop-police-career-bar'],
    objectives: [
      objective('background-check', 'Submit to a local background check', 'career-check', { arg: 'dreamdrop-police' }),
      objective('academy-info', 'Meet the academy coordinator', 'talk-topic', { arg: 'police-academy' }),
      objective('crossing-detail', 'Complete school crossing training', 'police-training', { arg: 'crossing' }),
    ],
    rewards: { money: 300, flags: ['dreamdrop-police-applicant'] },
  }),

  quest({
    id: 'arrival-fishing-harbor', title: 'Salt in the Air', category: 'story', townId: 'fishing-harbor',
    summary: 'Physically reach Fishing Harbor, register at Harbor Center, and learn the working coast.',
    prerequisites: ['open-roads'],
    objectives: [
      objective('reach-harbor', 'Drive to Fishing Harbor', 'enter-town', { arg: 'fishing-harbor' }),
      objective('harbor-map', 'Register at Harbor Center', 'sync-town-node', { arg: 'fishing-harbor' }),
      objective('meet-odell', 'Meet Cap Odell', 'talk-npc', { arg: 'cap-odell' }),
    ],
    rewards: { money: 400, flags: ['fishing-harbor-discovered'] },
    unlocks: ['fish-stories', 'harbor-honest-work'],
  }),
  quest({
    id: 'arrival-rich-hills', title: 'Past the Gate', category: 'story', townId: 'rich-hills',
    summary: 'Enter Rich Hills, register at Civic Crest, and learn who keeps the polished town running.',
    prerequisites: ['open-roads'],
    objectives: [
      objective('reach-rich', 'Drive to Rich Hills', 'enter-town', { arg: 'rich-hills' }),
      objective('rich-map', 'Synchronize Civic Crest', 'sync-town-node', { arg: 'rich-hills' }),
      objective('meet-service', 'Meet a Service Village worker', 'talk-topic', { arg: 'rich-hills-work' }),
    ],
    rewards: { money: 400, flags: ['rich-hills-discovered'] },
    unlocks: ['tunnel-vision', 'work-your-way-in'],
  }),
  quest({
    id: 'harbor-honest-work', title: 'Earn From the Catch', category: 'career', townId: 'fishing-harbor',
    summary: 'Complete honest harbor work before the rare-fish mystery begins.',
    prerequisites: ['arrival-fishing-harbor'],
    objectives: [
      objective('permit', 'Earn a beginner fishing permit', 'certificate-earned', { arg: 'harbor-fishing' }),
      objective('three-fish', 'Catch 3 legal fish', 'fish-caught', { count: 3 }),
      objective('sell-catch', 'Sell a catch at TideTable Market', 'sell-item', { arg: 'fish' }),
    ],
    rewards: { money: 500, reputation: { 'fishing-harbor': 1 }, flags: ['harbor-worker-known'] },
  }),
  quest({
    id: 'work-your-way-in', title: 'Work Your Way In', category: 'career', townId: 'rich-hills',
    summary: 'Prove that Rich Hills is more than a shopping trip by completing real service work.',
    prerequisites: ['arrival-rich-hills'], completionMode: 'any',
    objectives: [
      objective('valet', 'Complete a valet shift', 'job-special-complete', { arg: 'rich-valet' }),
      objective('estate', 'Complete an estate service call', 'job-special-complete', { arg: 'estate-helper' }),
      objective('landscape', 'Complete a landscaping route', 'job-special-complete', { arg: 'rich-landscape' }),
    ],
    rewards: { money: 700, reputation: { 'rich-hills': 1 }, flags: ['rich-hills-worker-known'] },
  }),

  quest({
    id: 'tunnel-vision', title: 'Tunnel Vision', category: 'story', townId: 'tech-city',
    summary: 'Reach TechTown physically through the Rich Hills tunnel.',
    prerequisites: ['arrival-rich-hills'],
    objectives: [
      objective('reach-tech', 'Drive through the tunnel into TechTown', 'enter-town', { arg: 'tech-city' }),
      objective('sync-tech', 'Synchronize GridLine Transit Hub', 'sync-town-node', { arg: 'tech-city' }),
    ],
    rewards: { money: 500, flags: ['tech-city-discovered'] },
    unlocks: ['signal-in-the-crowd'],
  }),
  quest({
    id: 'signal-in-the-crowd', title: 'A Signal in the Crowd', category: 'people', townId: 'tech-city', giverId: 'priya-shah',
    summary: 'Meet Priya and investigate why GridLink beacons are dropping safe-arrival handshakes.',
    prerequisites: ['tunnel-vision'],
    objectives: [
      objective('meet-priya', 'Meet Priya at CodeNest', 'talk-npc', { arg: 'priya-shah' }),
      objective('scan-beacon', 'Scan the Neon Core beacon', 'inspect-object', { arg: 'gridlink-beacon-neon' }),
    ],
    rewards: { money: 600, relationship: { 'priya-shah': 8 }, flags: ['gridlink-investigation-started'] },
    unlocks: ['gridlink-dead-zone'],
  }),
  quest({
    id: 'gridlink-dead-zone', title: 'Dead Zone', category: 'story', townId: 'tech-city', secret: true,
    summary: 'Repair a synchronization beacon in a camera-heavy service corridor.',
    prerequisites: ['signal-in-the-crowd'],
    objectives: [
      objective('reach-dead-zone', 'Reach the dead synchronization zone', 'reach-location', { arg: 'gridlink-dead-zone' }),
      objective('repair-beacon', 'Repair the beacon handshake', 'tech-puzzle-complete', { arg: 'gridlink-beacon' }),
    ],
    rewards: { money: 850, flags: ['gridlink-beacon-repaired'] },
    unlocks: ['wrong-address'],
  }),
  quest({
    id: 'wrong-address', title: 'Wrong Address', category: 'story', townId: 'tech-city', secret: true,
    summary: 'Recover a package that arrived at an unsafe test pad and determine whether the error was accidental.',
    prerequisites: ['gridlink-dead-zone'], consequenceRefs: ['gridlink-sabotage-choice'],
    objectives: [
      objective('recover-package', 'Recover the misplaced package', 'collect-item', { arg: 'gridlink-test-package' }),
      objective('inspect-log', 'Inspect the test-pad route log', 'tech-puzzle-complete', { arg: 'gridlink-route-log' }),
      objective('report-choice', 'Report, hide, or investigate the suspicious route', 'story-choice', { arg: 'gridlink-log-outcome' }),
    ],
    rewards: { money: 1000, flags: ['gridlink-route-incident-resolved'] },
    unlocks: ['three-points-make-a-grid'],
  }),
  quest({
    id: 'three-points-make-a-grid', title: 'Three Points Make a Grid', category: 'story', townId: 'tech-city',
    summary: 'Physically synchronize three existing towns before personal teleport access is considered safe.',
    prerequisites: ['wrong-address'],
    objectives: [
      objective('sync-starter', 'Synchronize Starter Town', 'sync-town-node', { arg: 'starter-town' }),
      objective('sync-harbor', 'Synchronize Fishing Harbor', 'sync-town-node', { arg: 'fishing-harbor' }),
      objective('sync-rich', 'Synchronize Rich Hills', 'sync-town-node', { arg: 'rich-hills' }),
    ],
    rewards: { money: 1250, flags: ['gridlink-three-node-certified'] },
    unlocks: ['mobility-certification'],
  }),
  quest({
    id: 'mobility-certification', title: 'Mobility Certification', category: 'career', townId: 'tech-city',
    summary: 'Prove you understand safe arrivals, blocked states, and why GridLink cannot erase discovery.',
    prerequisites: ['three-points-make-a-grid'],
    objectives: [
      objective('safe-arrival-test', 'Complete the safe-arrival test', 'certificate-earned', { arg: 'gridlink-safety' }),
      objective('blocked-state-test', 'Pass the blocked-state scenario', 'tech-puzzle-complete', { arg: 'gridlink-blocked-states' }),
    ],
    rewards: { money: 1500, flags: ['gridlink-purchase-eligible'] },
    unlocks: ['price-of-convenience'],
  }),
  quest({
    id: 'price-of-convenience', title: 'The Price of Convenience', category: 'story', townId: 'tech-city',
    summary: 'Purchase the GridLink Personal Teleporter for 250,000 DreamBucks.',
    prerequisites: ['mobility-certification'],
    objectives: [objective('buy-gridlink', 'Purchase GridLink at Gadget Forge Mobility Lab', 'purchase-item', { arg: 'gridlink-personal-teleporter' })],
    rewards: { money: 25000, items: ['gridlink-casing-founder'], flags: ['owns-gridlink'] },
    unlocks: ['now-you-see-me'],
  }),
  quest({
    id: 'now-you-see-me', title: 'Now You See Me', category: 'story', townId: 'tech-city',
    summary: 'Complete the first successful personal teleport.',
    prerequisites: ['price-of-convenience'],
    objectives: [objective('first-teleport', 'Use GridLink successfully', 'gridlink-teleport-success')],
    rewards: { money: 2500, flags: ['gridlink-first-jump'], achievements: ['worth-the-trip'] },
  }),

  quest({
    id: 'fish-stories', title: 'Fish Stories', category: 'people', townId: 'fishing-harbor', giverId: 'cap-odell',
    summary: 'Harbor workers disagree about a glowing fish and a signal beneath Lighthouse Point.',
    prerequisites: ['arrival-fishing-harbor'],
    objectives: [
      objective('hear-three-stories', 'Hear 3 versions of the glowing-fish story', 'talk-topic', { arg: 'gillyfish-rumor', count: 3 }),
      objective('ask-odell', 'Ask Cap Odell what he believes', 'talk-topic', { arg: 'odell-gillyfish' }),
    ],
    rewards: { money: 250, flags: ['gillyfish-rumor-known'] },
    unlocks: ['permit-to-go-deep'],
  }),
  quest({
    id: 'permit-to-go-deep', title: 'Permit to Go Deep', category: 'career', townId: 'fishing-harbor',
    summary: 'Earn the water-safety and deep-fishing credentials needed for Lighthouse Trench.',
    prerequisites: ['fish-stories'],
    objectives: [
      objective('water-safety', 'Earn water-safety certification', 'certificate-earned', { arg: 'water-safety' }),
      objective('deep-fishing', 'Earn a deep-fishing permit', 'certificate-earned', { arg: 'deep-fishing' }),
      objective('boat-route', 'Complete the Deepwater Buoy route', 'boat-course-complete', { arg: 'deepwater-buoy' }),
    ],
    rewards: { money: 700, flags: ['deepwater-eligible'] },
    unlocks: ['lighthouse-static'],
  }),
  quest({
    id: 'lighthouse-static', title: 'Lighthouse Static', category: 'story', townId: 'fishing-harbor', secret: true,
    summary: 'Repair a damaged lighthouse signal and trace the impossible reply from below.',
    prerequisites: ['permit-to-go-deep'],
    objectives: [
      objective('reach-lighthouse', 'Reach Lighthouse Point after dusk', 'reach-location', { arg: 'lighthouse-point' }),
      objective('repair-signal', 'Repair the lighthouse signal', 'repair-complete', { arg: 'lighthouse-signal' }),
      objective('trace-reply', 'Trace the deep sonar reply', 'sonar-puzzle-complete', { arg: 'lighthouse-reply' }),
    ],
    rewards: { money: 900, flags: ['trench-anomaly-located'] },
    unlocks: ['catch-that-watches-back'],
  }),
  quest({
    id: 'catch-that-watches-back', title: 'The Catch That Watches Back', category: 'story', townId: 'fishing-harbor', secret: true,
    summary: 'Catch a Gillyfish in an eligible deep-water location. Pity protection guarantees the hunt cannot last forever.',
    prerequisites: ['lighthouse-static'],
    objectives: [objective('catch-gillyfish', 'Catch a Gillyfish', 'fish-caught', { arg: 'gillyfish' })],
    rewards: { money: 1500, items: ['gillyfish'], flags: ['caught-first-gillyfish'] },
    unlocks: ['gillyfish-decision'],
  }),
  quest({
    id: 'gillyfish-decision', title: 'One Fish, Three Futures', category: 'story', townId: 'fishing-harbor', secret: true,
    summary: 'Consume, store, sell, or gift the Gillyfish. Every choice preserves a route forward, but not the same route.',
    prerequisites: ['catch-that-watches-back'], consequenceRefs: ['first-gillyfish-choice'],
    objectives: [objective('decide-gillyfish', 'Choose what to do with the Gillyfish', 'story-choice', { arg: 'first-gillyfish' })],
    rewards: { flags: ['first-gillyfish-choice-made'] },
    unlocks: ['breathe-different', 'one-that-got-away'],
  }),
  quest({
    id: 'breathe-different', title: 'Breathe Different', category: 'story', townId: 'fishing-harbor', secret: true,
    summary: 'Consume a Gillyfish and permanently gain Gillbound Adaptation.',
    prerequisites: ['gillyfish-decision'],
    objectives: [objective('consume-gillyfish', 'Consume a Gillyfish', 'consume-item', { arg: 'gillyfish' })],
    rewards: { flags: ['hasPermanentGills', 'gillbound-adaptation'], achievements: ['breathe-different'] },
    unlocks: ['something-changed'],
  }),
  quest({
    id: 'one-that-got-away', title: 'The One That Got Away', category: 'people', townId: 'fishing-harbor', secret: true,
    summary: 'Recover biological access after selling, storing, or gifting the first Gillyfish.',
    prerequisites: ['gillyfish-decision'], completionMode: 'any',
    objectives: [
      objective('catch-another', 'Catch another Gillyfish', 'fish-caught', { arg: 'gillyfish' }),
      objective('recover-buyer', 'Recover the original through the buyer storyline', 'recover-item', { arg: 'gillyfish' }),
      objective('receive-gift', 'Receive a Gillyfish from another player', 'receive-item', { arg: 'gillyfish' }),
    ],
    rewards: { flags: ['gillyfish-route-restored'] },
    unlocks: ['breathe-different'],
  }),
  quest({
    id: 'something-changed', title: 'Something Changed', category: 'people', townId: 'fishing-harbor', giverId: 'cap-odell', secret: true,
    summary: 'Let Harbor Academy confirm the adaptation and prepare you for the current anomaly.',
    prerequisites: ['breathe-different'],
    objectives: [
      objective('odell-recognizes', 'Speak with Cap Odell', 'talk-topic', { arg: 'gillbound-confirmation' }),
      objective('academy-exam', 'Complete the adaptation exam', 'certificate-earned', { arg: 'gillbound-navigation' }),
    ],
    rewards: { money: 1000, flags: ['aqualume-discovery-route-active'] },
    unlocks: ['lighthouse-trench'],
  }),
  quest({
    id: 'lighthouse-trench', title: 'The Lighthouse Trench', category: 'story', townId: 'fishing-harbor', secret: true,
    summary: 'Swim the marked current route through ruins, wreckage, and deep pressure warnings.',
    prerequisites: ['something-changed'],
    objectives: [
      objective('enter-trench', 'Enter Lighthouse Trench', 'reach-location', { arg: 'lighthouse-trench' }),
      objective('current-rings', 'Pass through 8 current rings', 'current-ring', { count: 8 }),
      objective('trench-shelter', 'Reach the deep emergency shelter', 'reach-location', { arg: 'trench-shelter' }),
    ],
    rewards: { money: 1800, flags: ['trench-route-complete'] },
    unlocks: ['no-more-surface'],
  }),
  quest({
    id: 'no-more-surface', title: 'No More Surface', category: 'story', townId: 'aqualume', secret: true,
    summary: 'Continue beyond the last easy return point and trust the route beneath Crownwater.',
    prerequisites: ['lighthouse-trench'],
    objectives: [
      objective('cross-deep-current', 'Cross the deep-current boundary', 'reach-location', { arg: 'aqualume-approach' }),
      objective('follow-sonar', 'Follow the hidden sonar path', 'sonar-route-complete', { arg: 'aqualume-approach' }),
    ],
    rewards: { money: 2000, flags: ['aqualume-gate-reached'] },
    unlocks: ['gate-wakes'],
  }),
  quest({
    id: 'gate-wakes', title: 'The Gate Wakes', category: 'story', townId: 'aqualume', secret: true,
    summary: 'Route the currents and activate the Aqualume Gate.',
    prerequisites: ['no-more-surface'],
    objectives: [
      objective('gate-current', 'Complete the gate current-routing puzzle', 'current-puzzle-complete', { arg: 'aqualume-gate' }),
      objective('activate-gate', 'Activate the Aqualume Gate', 'activate-object', { arg: 'aqualume-gate' }),
    ],
    rewards: { money: 2500, flags: ['hasDiscoveredAqualume'] },
    unlocks: ['crown-of-the-deep'],
  }),
  quest({
    id: 'crown-of-the-deep', title: 'Crown of the Deep', category: 'story', townId: 'aqualume', secret: true,
    summary: 'Enter Aqualume and reach Moonpool Gateway.',
    prerequisites: ['gate-wakes'],
    objectives: [
      objective('enter-aqualume', 'Enter Aqualume', 'enter-town', { arg: 'aqualume' }),
      objective('moonpool', 'Reach Moonpool Gateway', 'reach-location', { arg: 'moonpool-gateway' }),
    ],
    rewards: { money: 3000, achievements: ['beneath-crownwater'], flags: ['aqualume-arrived'] },
    unlocks: ['visitor-or-resident'],
  }),
  quest({
    id: 'visitor-or-resident', title: 'Visitor or Resident?', category: 'story', townId: 'aqualume', secret: true,
    summary: 'Register your reason for coming: explore, work, study, protect, or build a second home.',
    prerequisites: ['crown-of-the-deep'], consequenceRefs: ['aqualume-first-intent'],
    objectives: [objective('choose-intent', 'Choose your first Aqualume path', 'story-choice', { arg: 'aqualume-intent' })],
    rewards: { items: ['aqualume-visitor-permit', 'sea-scooter-rental-voucher'], flags: ['aqualume-registered'] },
    unlocks: ['under-new-pressure'],
  }),
  quest({
    id: 'under-new-pressure', title: 'Under New Pressure', category: 'story', townId: 'aqualume', secret: true,
    summary: 'Complete city orientation and synchronize the Moonpool GridLink node.',
    prerequisites: ['visitor-or-resident'],
    objectives: [
      objective('current-lane', 'Complete current-lane orientation', 'current-course-complete', { arg: 'aqualume-intro' }),
      objective('sync-moonpool', 'Synchronize Moonpool Gateway', 'sync-town-node', { arg: 'aqualume' }),
    ],
    rewards: { money: 5000, flags: ['aqualume-moonpool-synchronized'] },
  }),

  quest({ id: 'arrival-casino-strip', title: 'Across the Neon Bridge', category: 'story', townId: 'casino-strip', summary: 'Physically discover Casino Strip and synchronize its transit terminal.', prerequisites: ['arrival-fishing-harbor'], objectives: [objective('enter-casino', 'Enter Casino Strip', 'enter-town', { arg: 'casino-strip' }), objective('sync-casino', 'Synchronize Strip Transit Terminal', 'sync-town-node', { arg: 'casino-strip' })], rewards: { money: 500, flags: ['casino-strip-discovered'] } }),
  quest({ id: 'arrival-dungeon-outskirts', title: 'Where the Streetlights End', category: 'story', townId: 'dungeon-outskirts', summary: 'Leave TechTown by the utility road and reach the Outskirts safely.', prerequisites: ['tunnel-vision'], objectives: [objective('enter-dungeon-town', 'Enter Dungeon Outskirts', 'enter-town', { arg: 'dungeon-outskirts' }), objective('return-shrine', 'Synchronize the Return Shrine', 'sync-town-node', { arg: 'dungeon-outskirts' })], rewards: { money: 600, flags: ['dungeon-outskirts-discovered'] } }),
  quest({ id: 'arrival-obby-canyon', title: 'The Canyon Opens', category: 'story', townId: 'obby-canyon', summary: 'Follow the trail from the Outskirts into Obby Canyon and register at Base Camp.', prerequisites: ['arrival-dungeon-outskirts'], objectives: [objective('enter-obby', 'Enter Obby Canyon', 'enter-town', { arg: 'obby-canyon' }), objective('sync-obby', 'Synchronize Course Select Plaza', 'sync-town-node', { arg: 'obby-canyon' })], rewards: { money: 600, flags: ['obby-canyon-discovered'] } }),
  quest({ id: 'arrival-starline-city', title: 'Past the Marquee', category: 'story', townId: 'starline-city', summary: 'Reach Starline City from Casino Strip and register at FameLine Station.', prerequisites: ['arrival-casino-strip'], objectives: [objective('enter-starline', 'Enter Starline City', 'enter-town', { arg: 'starline-city' }), objective('sync-starline', 'Synchronize FameLine Station', 'sync-town-node', { arg: 'starline-city' })], rewards: { money: 700, flags: ['starline-city-discovered'] } }),
  quest({ id: 'make-your-mark', title: 'Make Your Mark', category: 'story', townId: 'world', secret: true, summary: 'Reach meaningful standing across the world and unlock a personalized “Your Story So Far” montage.', prerequisites: ['under-new-pressure', 'arrival-casino-strip', 'arrival-dungeon-outskirts', 'arrival-obby-canyon', 'arrival-starline-city'], objectives: [objective('world-standing', 'Earn recognition in every discovered town', 'world-standing-complete')], rewards: { money: 25000, achievements: ['zaylins-local-legend'], flags: ['make-your-mark-complete'] } }),
]);

export const QUESTS_BY_ID = freeze(Object.fromEntries(QUEST_CATALOG.map((entry) => [entry.id, entry])));

export const LEGACY_MISSION_ORDER = freeze([
  'welcome-to-dreamdrop',
  'chicken-run',
  'frostbox-first-look',
  'dealership-tour',
  'get-around-town',
  'home-haircut',
  'gym-intro',
  'school-intro',
  'first-job',
  'cleanup-crew',
  'street-trouble',
  'risky-choice',
  'police-alert',
]);

export function runtimeQuestIds() {
  return QUEST_CATALOG.filter((entry) => entry.implementation === QUEST_IMPLEMENTATION.runtime).map((entry) => entry.id);
}

export default QUEST_CATALOG;
