// ─────────────────────────────────────────────────────────────────────────────
// starterTownDistrictProfiles.js — Phase 5B/6A district identity contracts.
//
// Pure data consumed by massing, traffic, pedestrian, police, lighting, audio,
// weather, and streaming systems. These values describe identity without tying
// gameplay to a particular GLB or parcel coordinate.
// ─────────────────────────────────────────────────────────────────────────────

const freeze = (value) => Object.freeze(value);
const profile = (id, values) => freeze({ id, ...values });

export const STARTER_TOWN_DISTRICT_PROFILES = freeze([
  profile('dreamdrop-district', {
    palette: freeze(['#8b765f', '#5f6574', '#b88756', '#446c72', '#d8c39d']),
    buildingScale: freeze({ minFloors: 2, maxFloors: 8, landmarkFloors: 12 }),
    roofline: 'mixed historic parapets, compact towers, rooftop signs and water tanks',
    density: 0.88,
    parcelDensity: 0.9,
    skylineRange: freeze({ min: 10, max: 52 }),
    roadTreatment: 'busy mixed-use curb, frequent crossings, loading pockets and painted bus zones',
    vegetation: freeze({ density: 0.32, types: ['street-tree', 'planter', 'pocket-tree'] }),
    lighting: freeze({ temperature: 'warm-neutral', intensity: 1, neon: 0.55, nightWindows: 0.82 }),
    signage: freeze({ density: 0.9, style: 'stacked storefront, painted wall, projecting blade signs' }),
    ambience: freeze(['city-core', 'storefront-chatter', 'distant-traffic']),
    traffic: freeze({ density: 0.92, speedScale: 0.72, mix: ['compact', 'sedan', 'delivery', 'taxi', 'police'] }),
    pedestrians: freeze({ density: 1, mix: ['resident', 'student', 'shopper', 'worker', 'visitor'] }),
    police: freeze({ coverage: 0.9, patrol: 'frequent-foot-and-cruiser', responseScale: 0.82 }),
    cleanliness: 0.66,
    weatherResponse: freeze(['awning-drips', 'puddle-curbs', 'wet-neon-reflection']),
    services: freeze(['retail', 'food', 'jewelry', 'tutorial', 'transit', 'police-response']),
  }),
  profile('market-mile', {
    palette: freeze(['#9a6f62', '#d0a26f', '#475f67', '#896f93', '#ded3bd']),
    buildingScale: freeze({ minFloors: 1, maxFloors: 6, landmarkFloors: 8 }),
    roofline: 'continuous retail rows, corner marquees and occasional apartment floors above shops',
    density: 0.84,
    parcelDensity: 0.88,
    skylineRange: freeze({ min: 8, max: 34 }),
    roadTreatment: 'storefront parking, delivery alleys, wide crossings and short curb turnover',
    vegetation: freeze({ density: 0.38, types: ['street-tree', 'planter', 'median-shrub'] }),
    lighting: freeze({ temperature: 'warm', intensity: 1.05, neon: 0.72, nightWindows: 0.76 }),
    signage: freeze({ density: 1, style: 'retail marquees, window graphics and colorful blade signs' }),
    ambience: freeze(['retail-strip', 'delivery-bays', 'music-leak']),
    traffic: freeze({ density: 0.86, speedScale: 0.68, mix: ['compact', 'sedan', 'delivery', 'rideshare'] }),
    pedestrians: freeze({ density: 0.94, mix: ['shopper', 'worker', 'student', 'visitor'] }),
    police: freeze({ coverage: 0.72, patrol: 'retail-corridor', responseScale: 0.92 }),
    cleanliness: 0.78,
    weatherResponse: freeze(['shop-awning-drips', 'parking-puddles', 'window-condensation']),
    services: freeze(['fashion', 'food', 'retail-jobs', 'delivery', 'parking']),
  }),
  profile('northworks-auto-row', {
    palette: freeze(['#665f57', '#41464e', '#8b4f3b', '#9a8b6a', '#c4c8c9']),
    buildingScale: freeze({ minFloors: 1, maxFloors: 5, landmarkFloors: 7 }),
    roofline: 'wide industrial sheds, sawtooth roofs, garage doors, signs and service stacks',
    density: 0.58,
    parcelDensity: 0.62,
    skylineRange: freeze({ min: 7, max: 30 }),
    roadTreatment: 'broad lanes, truck turns, loading aprons, cracked shoulders and fenced service roads',
    vegetation: freeze({ density: 0.13, types: ['hardy-tree', 'weed-strip', 'buffer-shrub'] }),
    lighting: freeze({ temperature: 'cool-neutral', intensity: 0.82, neon: 0.2, nightWindows: 0.42 }),
    signage: freeze({ density: 0.58, style: 'large roof signs, pole signs, yard numbers and safety placards' }),
    ambience: freeze(['industrial-hum', 'garage-tools', 'truck-airbrakes']),
    traffic: freeze({ density: 0.68, speedScale: 0.86, mix: ['pickup', 'van', 'truck', 'tow', 'sedan'] }),
    pedestrians: freeze({ density: 0.34, mix: ['mechanic', 'worker', 'customer', 'driver'] }),
    police: freeze({ coverage: 0.58, patrol: 'vehicle-heavy', responseScale: 1.08 }),
    cleanliness: 0.5,
    weatherResponse: freeze(['oil-sheen-puddles', 'roof-runoff', 'muddy-yard-edges']),
    services: freeze(['vehicle-sales', 'repair', 'towing', 'industrial-jobs', 'loading']),
  }),
  profile('scholars-quarter', {
    palette: freeze(['#6f8c79', '#c3ad7b', '#6b7791', '#a76b55', '#e3dcc6']),
    buildingScale: freeze({ minFloors: 1, maxFloors: 5, landmarkFloors: 7 }),
    roofline: 'campus wings, gym volumes, pitched neighborhood roofs and a few academic towers',
    density: 0.57,
    parcelDensity: 0.6,
    skylineRange: freeze({ min: 7, max: 32 }),
    roadTreatment: 'school loop, raised crossings, drop-off bays, bike racks and slower local streets',
    vegetation: freeze({ density: 0.72, types: ['shade-tree', 'campus-lawn', 'hedge', 'flower-bed'] }),
    lighting: freeze({ temperature: 'neutral-warm', intensity: 0.88, neon: 0.05, nightWindows: 0.5 }),
    signage: freeze({ density: 0.45, style: 'campus monuments, wayfinding, crossing and activity boards' }),
    ambience: freeze(['campus', 'playground-distant', 'birds']),
    traffic: freeze({ density: 0.55, speedScale: 0.52, mix: ['sedan', 'family-suv', 'school-van', 'service'] }),
    pedestrians: freeze({ density: 0.82, mix: ['student', 'teacher', 'parent', 'resident'] }),
    police: freeze({ coverage: 0.76, patrol: 'school-zone', responseScale: 0.9 }),
    cleanliness: 0.9,
    weatherResponse: freeze(['covered-walkway-drips', 'field-puddles', 'wet-leaf-paths']),
    services: freeze(['education', 'youth-services', 'health', 'sports', 'school-jobs']),
  }),
  profile('civic-heights', {
    palette: freeze(['#6c7893', '#c8c2b2', '#4f5b70', '#8f7658', '#9aa69a']),
    buildingScale: freeze({ minFloors: 2, maxFloors: 10, landmarkFloors: 18 }),
    roofline: 'formal civic blocks, office towers, stepped hill silhouettes and public monuments',
    density: 0.67,
    parcelDensity: 0.68,
    skylineRange: freeze({ min: 12, max: 78 }),
    roadTreatment: 'graded avenues, formal medians, service drives, secure parking and retaining walls',
    vegetation: freeze({ density: 0.55, types: ['formal-tree', 'hedge', 'civic-lawn', 'terrace-planter'] }),
    lighting: freeze({ temperature: 'neutral', intensity: 0.96, neon: 0.08, nightWindows: 0.7 }),
    signage: freeze({ density: 0.42, style: 'monument signs, civic seals, directional pylons and building names' }),
    ambience: freeze(['civic-plaza', 'office-district', 'wind-on-hill']),
    traffic: freeze({ density: 0.7, speedScale: 0.76, mix: ['sedan', 'service', 'police', 'municipal', 'delivery'] }),
    pedestrians: freeze({ density: 0.62, mix: ['worker', 'visitor', 'officer', 'courier'] }),
    police: freeze({ coverage: 1, patrol: 'headquarters-and-civic', responseScale: 0.7 }),
    cleanliness: 0.94,
    weatherResponse: freeze(['retaining-wall-runoff', 'granite-reflections', 'wind-driven-rain']),
    services: freeze(['government', 'police', 'careers', 'banking', 'public-services', 'health']),
  }),
  profile('eastgate-corridor', {
    palette: freeze(['#8c805c', '#49666c', '#b66b42', '#5f5f62', '#d8cfaa']),
    buildingScale: freeze({ minFloors: 1, maxFloors: 5, landmarkFloors: 8 }),
    roofline: 'roadside services, fuel canopy, travel signs and low commercial strips',
    density: 0.48,
    parcelDensity: 0.52,
    skylineRange: freeze({ min: 6, max: 34 }),
    roadTreatment: 'parkway frontage, turn pockets, travel plazas, shoulders and gateway signage',
    vegetation: freeze({ density: 0.34, types: ['median-tree', 'buffer-shrub', 'roadside-grass'] }),
    lighting: freeze({ temperature: 'cool-bright', intensity: 1.04, neon: 0.38, nightWindows: 0.5 }),
    signage: freeze({ density: 0.72, style: 'highway pylons, fuel-price boards and directional signs' }),
    ambience: freeze(['roadside', 'fuel-station', 'parkway-traffic']),
    traffic: freeze({ density: 0.78, speedScale: 0.94, mix: ['sedan', 'suv', 'van', 'truck', 'traveler'] }),
    pedestrians: freeze({ density: 0.3, mix: ['traveler', 'worker', 'customer', 'courier'] }),
    police: freeze({ coverage: 0.7, patrol: 'gateway-and-traffic', responseScale: 0.88 }),
    cleanliness: 0.72,
    weatherResponse: freeze(['canopy-runoff', 'headlight-reflection', 'windblown-litter']),
    services: freeze(['fuel', 'charging', 'travel', 'convenience', 'delivery', 'gateway']),
  }),
  profile('parkside-commons', {
    palette: freeze(['#5f8666', '#8d9d72', '#8b6e52', '#5f6f7b', '#d3cba7']),
    buildingScale: freeze({ minFloors: 1, maxFloors: 4, landmarkFloors: 6 }),
    roofline: 'open park canopy, recreation halls, gym volume and low residential edges',
    density: 0.3,
    parcelDensity: 0.38,
    skylineRange: freeze({ min: 5, max: 26 }),
    roadTreatment: 'crescent roads, roundabout, trail crossings, controlled parking and traffic calming',
    vegetation: freeze({ density: 0.92, types: ['mature-tree', 'park-lawn', 'flower-bed', 'trail-shrub'] }),
    lighting: freeze({ temperature: 'warm-soft', intensity: 0.72, neon: 0.03, nightWindows: 0.35 }),
    signage: freeze({ density: 0.3, style: 'park maps, trail markers, recreation and rules signs' }),
    ambience: freeze(['park', 'recreation', 'birds-and-wind']),
    traffic: freeze({ density: 0.38, speedScale: 0.58, mix: ['family-suv', 'compact', 'service', 'bike-rack-van'] }),
    pedestrians: freeze({ density: 0.72, mix: ['resident', 'athlete', 'family', 'walker', 'worker'] }),
    police: freeze({ coverage: 0.58, patrol: 'community-and-park', responseScale: 1.02 }),
    cleanliness: 0.88,
    weatherResponse: freeze(['trail-puddles', 'wet-grass', 'tree-drip', 'shelter-use']),
    services: freeze(['recreation', 'fitness', 'park', 'sanitation', 'community']),
  }),
  profile('willowbend-residential', {
    palette: freeze(['#7d8b70', '#b79272', '#7b6f83', '#66838b', '#ded5bd']),
    buildingScale: freeze({ minFloors: 1, maxFloors: 3, landmarkFloors: 4 }),
    roofline: 'pitched homes, porches, attached garages and quiet neighborhood silhouettes',
    density: 0.44,
    parcelDensity: 0.58,
    skylineRange: freeze({ min: 5, max: 18 }),
    roadTreatment: 'local streets, cul-de-sacs, driveways, sidewalks, mailboxes and low-speed corners',
    vegetation: freeze({ density: 0.78, types: ['yard-tree', 'hedge', 'lawn', 'flower-bed'] }),
    lighting: freeze({ temperature: 'warm', intensity: 0.62, neon: 0, nightWindows: 0.48 }),
    signage: freeze({ density: 0.18, style: 'street names, neighborhood marker and house numbers' }),
    ambience: freeze(['quiet-residential', 'yard-birds', 'distant-city']),
    traffic: freeze({ density: 0.32, speedScale: 0.5, mix: ['family-suv', 'sedan', 'compact', 'delivery'] }),
    pedestrians: freeze({ density: 0.48, mix: ['resident', 'family', 'student', 'delivery'] }),
    police: freeze({ coverage: 0.52, patrol: 'neighborhood', responseScale: 1.08 }),
    cleanliness: 0.92,
    weatherResponse: freeze(['gutter-flow', 'driveway-puddles', 'porch-shelter', 'wet-lawns']),
    services: freeze(['housing', 'mail', 'home-upgrades', 'neighborhood', 'delivery']),
  }),
  profile('westside-blocks', {
    palette: freeze(['#775f76', '#8b6d55', '#4d6570', '#a47659', '#c7bca5']),
    buildingScale: freeze({ minFloors: 1, maxFloors: 6, landmarkFloors: 8 }),
    roofline: 'row housing, walk-ups, corner stores, courts, warehouse edges and alley fire stairs',
    density: 0.76,
    parcelDensity: 0.82,
    skylineRange: freeze({ min: 7, max: 38 }),
    roadTreatment: 'narrower locals, active alleys, curb parking, courts and utility-heavy back lanes',
    vegetation: freeze({ density: 0.35, types: ['street-tree', 'yard-tree', 'vacant-lot-grass'] }),
    lighting: freeze({ temperature: 'warm-neutral', intensity: 0.78, neon: 0.18, nightWindows: 0.66 }),
    signage: freeze({ density: 0.54, style: 'murals, corner-store signs, block markers and court signs' }),
    ambience: freeze(['neighborhood', 'basketball-court', 'alley-service']),
    traffic: freeze({ density: 0.62, speedScale: 0.62, mix: ['sedan', 'compact', 'pickup', 'delivery'] }),
    pedestrians: freeze({ density: 0.82, mix: ['resident', 'worker', 'student', 'shopper'] }),
    police: freeze({ coverage: 0.68, patrol: 'community-and-alley', responseScale: 0.94 }),
    cleanliness: 0.58,
    weatherResponse: freeze(['alley-puddles', 'downspout-runoff', 'wet-mural-sheen', 'windblown-litter']),
    services: freeze(['housing', 'supplies', 'community', 'courts', 'local-retail']),
  }),
]);

export const DISTRICT_PROFILE_BY_ID = freeze(Object.fromEntries(
  STARTER_TOWN_DISTRICT_PROFILES.map((entry) => [entry.id, entry]),
));

export function districtProfile(id) {
  return DISTRICT_PROFILE_BY_ID[id] || null;
}

export default STARTER_TOWN_DISTRICT_PROFILES;
