// ───────────────────────────────────────────────────────────────────────────
//  townThemes.js — per-town theme data skeleton (NOT wired into gameplay).
//
//  Pure data. One entry per town in docs/TOWN_ROADMAP.md, keyed by the `themeId`
//  referenced from src/config/worldMapPlan.js DISTRICTS. Holds the visual palette,
//  services, stores, minigames, NPC profiles, mission chains, economy, law rules,
//  and career references. These are design references for future towns.
// ───────────────────────────────────────────────────────────────────────────

export const TOWN_THEMES = Object.freeze({
  starter: {
    name: 'Starter Town',
    palette: { sky: '#9fc3e8', ground: '#5b6b52', accent: '#c8a24a', road: '#3a3d42' },
    mood: 'large everyday city and tutorial home base',
    services: ['police', 'public-safety', 'gym', 'fuel', 'food', 'home', 'school', 'property-desk', 'community-health'],
    stores: ['block-supply', 'mini-market', 'chicken-spot', 'frostbox', 'kicks-fits', 'auto-haus'],
    minigames: ['clippers-lineup', 'gym-training', 'food-shift', 'driving', 'school-foundations', 'road-test', 'delivery-route'],
    npcProfiles: ['shop-clerk', 'police-officer', 'police-cadet', 'gym-trainer', 'teacher', 'pedestrian', 'resident', 'commuter'],
    missionChains: ['intro-jobs', 'starter-law-choice', 'police-academy'],
    careers: ['police-officer', 'office-associate', 'garage-hand', 'food-service', 'sanitation', 'retail', 'courier'],
    careerRules: {
      policeOfficer: {
        localConvictionPermanentlyDisqualifies: true,
        uncaughtCrimeIgnoredByBackgroundCheck: true,
        outOfTownConvictionRequiresReform: true,
      },
    },
    economy: { wageTier: 'low-medium', priceTier: 'low' },
    legal: { policed: true, wantedSystem: true, criminalRecordsByTown: true },
  },
  fishing: {
    name: 'Fishing Harbor',
    palette: { sky: '#bcd6e6', ground: '#6b7d6a', accent: '#2f7fa8', road: '#4a4f55' },
    mood: 'coastal working harbor',
    services: ['harbor-master', 'harbor-patrol', 'harbor-academy', 'boat-repair', 'fuel-dock'],
    stores: ['bait-tackle', 'seafood-market', 'boat-rental', 'dockside-diner'],
    minigames: ['fishing', 'fish-transform', 'crab-traps', 'boat-buoy-run', 'market-rush'],
    npcProfiles: ['fisher', 'market-vendor', 'harbor-master', 'harbor-patrol-officer'],
    missionChains: ['fishing-quotas', 'gillyfish-discovery'],
    careers: ['harbor-patrol-officer', 'fisher', 'dockhand', 'boat-mechanic', 'market-worker'],
    economy: { wageTier: 'medium', priceTier: 'medium', special: 'fish-rarity-market' },
    legal: { policed: true, permits: ['fishing-permit'], criminalRecordsByTown: true },
  },
  dungeon: {
    name: 'Dungeon Outskirts',
    palette: { sky: '#3a3550', ground: '#2e2a33', accent: '#7a3b3b', road: '#26222a' },
    mood: 'sparse surface outpost and deep dungeon',
    services: ['healer', 'stash', 'shrine', 'warden-station', 'wayfarer-fuel'],
    stores: ['adventurer-supply', 'blacksmith', 'potions', 'relic-appraiser'],
    minigames: ['dungeon-crawl', 'boss-fight', 'trap-timing', 'relic-appraisal'],
    npcProfiles: ['blacksmith', 'healer', 'quest-giver', 'warden'],
    missionChains: ['dungeon-clears'],
    careers: ['warden-ranger', 'relic-runner', 'blacksmith-helper', 'potion-crafter'],
    economy: { wageTier: 'variable', priceTier: 'high', special: 'loot-economy' },
    legal: { policed: true, authority: 'warden', pve: true, criminalRecordsByTown: true },
  },
  obby: {
    name: 'Obby Canyon',
    palette: { sky: '#ffd9a0', ground: '#caa15a', accent: '#ff6f61', road: '#b3854a' },
    mood: 'canyon base and vertical platforming',
    services: ['respawn-beacon', 'leaderboard', 'ranger-station', 'first-aid', 'checkpoint-fuel'],
    stores: ['cosmetic-shop', 'checkpoint-pass'],
    minigames: ['obby-course', 'time-trial', 'no-fall', 'zipline-rings'],
    npcProfiles: ['course-host', 'cosmetic-vendor', 'canyon-ranger', 'maintenance-tech'],
    missionChains: ['obby-courses'],
    careers: ['canyon-ranger', 'course-marshal', 'maintenance-tech', 'parkour-coach'],
    economy: { wageTier: 'reward', priceTier: 'cosmetic' },
    legal: { policed: true, authority: 'ranger', fallReset: true, criminalRecordsByTown: true },
  },
  casino: {
    name: 'Casino Strip',
    palette: { sky: '#1a1030', ground: '#2a2140', accent: '#ff3da6', road: '#201838' },
    mood: 'neon entertainment city',
    services: ['bank', 'hotel', 'security', 'strip-police', 'clinic', 'transit', 'fuel'],
    stores: ['game-hall', 'arcade', 'prize-shop', 'luxury-boutique'],
    minigames: ['slots', 'blackjack', 'roulette', 'prize-wheel', 'arcade'],
    npcProfiles: ['game-attendant', 'hotel-worker', 'security-guard', 'strip-police-officer'],
    missionChains: ['hospitality-career', 'responsible-play'],
    careers: ['strip-police-officer', 'bellhop', 'security-spotter', 'arcade-attendant'],
    economy: { wageTier: 'variable', priceTier: 'high', special: 'controlled-game-currency' },
    legal: { policed: true, cheatingBanned: true, criminalRecordsByTown: true },
  },
  rich: {
    name: 'Rich Hills',
    palette: { sky: '#cfe6f2', ground: '#7fa36b', accent: '#d9c27a', road: '#454b50' },
    mood: 'wealthy hillside municipality',
    services: ['rich-hills-police', 'private-clinic', 'valet', 'estate-agent', 'marina', 'fuel'],
    stores: ['luxury-cars', 'real-estate', 'designer-fashion', 'jewelry'],
    minigames: ['golf', 'yacht-run', 'car-show', 'valet-dash'],
    npcProfiles: ['concierge', 'police-officer', 'private-security', 'estate-agent'],
    missionChains: ['concierge-errands'],
    careers: ['rich-hills-police-officer', 'valet', 'concierge', 'estate-helper', 'marina-worker'],
    economy: { wageTier: 'high', priceTier: 'luxury', special: 'property-income' },
    legal: { policed: true, privateSecurity: true, statusGated: true, criminalRecordsByTown: true },
  },
  tech: {
    name: 'TechTown',
    palette: { sky: '#0e1830', ground: '#2a3550', accent: '#36d3ff', road: '#1a2740' },
    mood: 'futuristic smart city',
    services: ['metro-security', 'clinic', 'transit-hub', 'charging', 'voltbyte-academy'],
    stores: ['electronics', 'drone-shop', 'gadget-lab', 'co-working'],
    minigames: ['coding-puzzle', 'drone-pilot', 'hacking', 'robot-repair'],
    npcProfiles: ['engineer', 'startup-founder', 'metro-security-officer', 'corp-security'],
    missionChains: ['debug-contracts'],
    careers: ['metro-security-officer', 'engineer', 'drone-dispatcher', 'robot-repair-tech'],
    economy: { wageTier: 'high', priceTier: 'medium', special: 'skill-pay' },
    legal: { policed: true, cybercrimeHeat: true, criminalRecordsByTown: true },
  },
  hollywood: {
    name: 'Starline City',
    palette: { sky: '#ffe0c0', ground: '#b89a6a', accent: '#ff4d6d', road: '#4a4038' },
    mood: 'studios, performance, and red carpets',
    services: ['starline-police', 'agency', 'studio', 'salon', 'clinic', 'academy', 'fuel'],
    stores: ['wardrobe', 'talent-agency', 'music-store'],
    minigames: ['rhythm-audition', 'dance-battle', 'talk-show', 'photo-shoot'],
    npcProfiles: ['agent', 'director', 'fan', 'starline-police-officer', 'stagehand'],
    missionChains: ['rising-star'],
    careers: ['starline-police-officer', 'background-extra', 'stagehand', 'wardrobe-runner'],
    economy: { wageTier: 'variable', priceTier: 'high', special: 'fame-reputation' },
    legal: { policed: true, scandalMeter: true, criminalRecordsByTown: true },
  },
  aqualume: {
    name: 'Aqualume',
    palette: { water: '#184f6b', glass: '#8de8ef', pearl: '#e4d8c8', coral: '#d66f7a', accent: '#74e0c2' },
    mood: 'luminous underwater final city',
    services: ['current-guard', 'tideglass-academy', 'clinic', 'bluecore-transit', 'housing', 'sanctuary'],
    stores: ['coral-market', 'salvage-shop', 'submarine-dealer', 'pearlworks'],
    minigames: ['current-surf', 'sea-scooter-slalom', 'sonar-mapping', 'salvage-scanner', 'coral-restoration'],
    npcProfiles: ['current-guard-officer', 'marine-engineer', 'sanctuary-warden', 'resident', 'sea-life-handler'],
    missionChains: ['aqualume-arrival', 'abyssal-progression'],
    careers: ['current-guard-officer', 'submarine-engineer', 'salvage-diver', 'sanctuary-worker'],
    economy: { wageTier: 'high', priceTier: 'high', special: 'advanced-certified-work' },
    legal: { policed: true, authority: 'current-guard', sonarPursuit: true, criminalRecordsByTown: true },
  },
});

export default TOWN_THEMES;