import { makeStoryPack } from '../storyFactory.js';

export const AQUALUME_STORY_PACK = makeStoryPack({
  townId: "aqualume",
  label: "Aqualume",
  baseMoney: 750,
  arcs: [
  {"id":"moonpool-citizen-orientation","name":"Moonpool Citizen Orientation","districtId":"moonpool-gateway","leadNpcId":"captain-lyra-current","leadNpcName":"Captain Lyra Current","leadRole":"Current Guard captain","personality":"measured-commanding","premise":"Aqualume citizenship introduces pressure rules, current lanes, surface visitors, emergency seals, housing, and local customs.","skill":"underwater navigation","coreTask":"complete orientation and public service tasks","complication":"surface tourists violate a protected district and spark resentment","routeA":"mediate fair visitor rules","routeB":"support strict closure of surface access","finale":"secure Moonpool during an emergency arrival","unlock":"residency, local services, and civic access","category":"story","tags":["aqualume","citizenship","navigation"]},
  {"id":"current-guard-career","name":"Current Guard Career","districtId":"guard-station","leadNpcId":"captain-lyra-current","leadNpcName":"Captain Lyra Current","leadRole":"Current Guard captain","personality":"measured-commanding","premise":"The player trains in underwater rescue, current law, transit safety, sanctuary rules, evidence, and deep-pressure response.","skill":"underwater law and rescue","coreTask":"complete guard patrols and rescues","complication":"a guard uses pressure laws to target surface-born residents","routeA":"report the discrimination","routeB":"protect the guard for institutional trust","finale":"resolve a citywide transit breach","unlock":"Current Guard rank progression","category":"career","tags":["police","rescue","aqualume"]},
  {"id":"deep-current-research","name":"Deep Current Research","districtId":"research-dome","leadNpcId":"dr-coral-banks","leadNpcName":"Dr. Coral Banks","leadRole":"oceanographer","personality":"excited-methodical","premise":"Scientists study currents, pressure, deep species, Gillyfish adaptation, and the limits of exploration.","skill":"deep-sea science","coreTask":"collect data and run current models","complication":"research could enable dangerous extraction at the Abyssal Edge","routeA":"restrict the data","routeB":"publish openly and trust oversight","finale":"complete the city's first full current map","unlock":"research career and deep-route forecasts","category":"career","tags":["science","currents","ethics"]},
  {"id":"life-support-heart","name":"Life Support Heart","districtId":"life-support-district","leadNpcId":"eng-tomas-blue","leadNpcName":"Engineer Tomas Blue","leadRole":"life-support engineer","personality":"calm-obsessive","premise":"Air, pressure, temperature, food systems, and emergency bulkheads make life support the hidden heart of the city.","skill":"engineering","coreTask":"maintain systems and diagnose failures","complication":"someone is diverting capacity to a private luxury dome","routeA":"restore fair distribution","routeB":"accept the diversion for funding","finale":"save the city during a cascading life-support emergency","unlock":"engineering career and infrastructure control","category":"career","tags":["engineering","infrastructure","aqualume"]},
  {"id":"sanctuary-of-motion","name":"Sanctuary of Motion","districtId":"sanctuary","leadNpcId":"sister-manta","leadNpcName":"Sister Manta","leadRole":"sanctuary keeper","personality":"gentle-firm","premise":"The player protects rays, dolphins, nurseries, migration routes, and the rule that friendly sea life is not property.","skill":"wildlife care","coreTask":"assist animals and protect habitats","complication":"a luxury program wants to sell exclusive animal rides","routeA":"keep guided partnerships non-ownable","routeB":"license private experiences for funding","finale":"defend the sanctuary during a migration event","unlock":"sanctuary career and guided traversal partnerships","category":"people","tags":["wildlife","ethics","travel"]},
  {"id":"sunken-salvage-guild","name":"Sunken Salvage Guild","districtId":"salvage-docks","leadNpcId":"mara-deep","leadNpcName":"Mara Deep","leadRole":"salvage captain","personality":"fearless-calculating","premise":"Salvage work involves wrecks, ownership, dangerous cargo, history, and the difference between recovery and theft.","skill":"salvage and appraisal","coreTask":"survey wrecks and recover cargo","complication":"a wreck belongs to a living surface family who never knew it was found","routeA":"return personal items and negotiate rights","routeB":"claim everything under deep-water law","finale":"complete a collapsing wreck extraction","unlock":"salvage guild rank and mini-sub contracts","category":"career","tags":["salvage","ownership","history"]},
  {"id":"bubble-transit-network","name":"Bubble Transit Network","districtId":"transit-ring","leadNpcId":"niko-bubble","leadNpcName":"Niko Bubble","leadRole":"transit dispatcher","personality":"fast-friendly","premise":"The city's bubble taxis and current tubes need routing, maintenance, accessibility, security, and emergency alternatives.","skill":"transit operations","coreTask":"dispatch routes and repair stations","complication":"an algorithm removes service from a low-income district","routeA":"override it and redesign the route model","routeB":"preserve efficiency and offer limited vouchers","finale":"keep transit moving during a gate closure","unlock":"transit career and fast-travel improvements","category":"career","tags":["transit","accessibility","technology"]},
  {"id":"deep-market-tides","name":"Deep Market Tides","districtId":"deep-market","leadNpcId":"mae-pearls","leadNpcName":"Mae Pearls","leadRole":"market broker","personality":"charming-watchful","premise":"Aqualume's market trades food, crafts, salvage, surface goods, rare materials, and information.","skill":"trade and negotiation","coreTask":"run stalls and verify goods","complication":"counterfeit pressure gear enters the market","routeA":"trace and remove it","routeB":"sell it to risky buyers for profit","finale":"protect the market during a current surge","unlock":"market ownership and cross-surface trade","category":"career","tags":["market","trade","investigation"]},
  {"id":"abyssal-edge-expedition","name":"Abyssal Edge Expedition","districtId":"abyssal-edge","leadNpcId":"commander-selene-depth","leadNpcName":"Commander Selene Depth","leadRole":"expedition leader","personality":"disciplined-awe-struck","premise":"The late-game expedition requires pressure gear, mini-subs, maps, rescue planning, and accepting that not every mystery should be opened.","skill":"deep expedition","coreTask":"prepare vehicles and complete pressure trials","complication":"the team finds a sealed structure emitting a citywide signal","routeA":"observe without opening it","routeB":"open it for knowledge and accept unknown consequences","finale":"return from the Abyssal Edge with the expedition intact","unlock":"abyssal routes, rare resources, and endgame events","category":"story","tags":["endgame","exploration","mystery"]},
  {"id":"surface-and-sea-accord","name":"Surface and Sea Accord","districtId":"civic-dome","leadNpcId":"ambassador-nia-wave","leadNpcName":"Ambassador Nia Wave","leadRole":"diplomat","personality":"patient-sharp","premise":"Surface towns and Aqualume negotiate travel, trade, research, law, environmental responsibility, and cultural respect.","skill":"diplomacy","coreTask":"meet delegations and draft agreements","complication":"a surface company demands extraction rights in exchange for infrastructure","routeA":"reject extraction and build slower partnerships","routeB":"accept controlled extraction for rapid development","finale":"ratify the first Crownwater Accord","unlock":"diplomatic missions and permanent cross-town state changes","category":"story","tags":["diplomacy","world","aqualume"]}
],
  supportNpcs: [
  {"id":"suri-shell","name":"Suri Shell","districtId":"moonpool-gateway","role":"visitor coordinator","personality":"calm-curious","goal":"make surface visitors respectful","fear":"the gate closing permanently","secret":"collects postcards from places she cannot visit dry","value":"hospitality","petPeeve":"tourists tapping habitat glass"},
  {"id":"kai-pressure","name":"Kai Pressure","districtId":"life-support-district","role":"maintenance diver","personality":"quiet-funny","goal":"keep leaks small and boring","fear":"a hidden structural crack","secret":"marks every repaired pipe with a tiny star","value":"maintenance","petPeeve":"any sentence beginning with 'it should hold'"}
],
});

export default AQUALUME_STORY_PACK;
