import { makeStoryPack } from '../storyFactory.js';

export const CASINO_STRIP_STORY_PACK = makeStoryPack({
  townId: "casino-strip",
  label: "Casino Strip",
  baseMoney: 500,
  arcs: [
  {"id":"grand-chance-dealer-track","name":"Grand Chance Dealer Track","districtId":"neon-plaza","leadNpcId":"vincent-luck","leadNpcName":"Vincent Luck","leadRole":"game hall dealer","personality":"silky-honest","premise":"The player learns probability, guest management, table procedure, cheating detection, and responsible limits.","skill":"probability and service","coreTask":"train at tables and manage guests","complication":"a popular regular is being manipulated by a dishonest host","routeA":"protect the guest and expose the host","routeB":"help the host maximize spending for status rewards","finale":"run the championship floor without a scandal","unlock":"dealer career and advanced game events","category":"career","tags":["games","probability","hospitality"]},
  {"id":"ticket-town-champion","name":"Ticket Town Champion","districtId":"arcade-district","leadNpcId":"miko-james","leadNpcName":"Miko James","leadRole":"arcade champion","personality":"competitive-goofy","premise":"A skill-based arcade arc covers cabinet mastery, repair, tournaments, prize economy, and sportsmanship.","skill":"arcade skill","coreTask":"master cabinet families and repair machines","complication":"a rival exploits a scoring bug before the city tournament","routeA":"report the bug and accept a reset","routeB":"use the bug once and risk disqualification","finale":"win the Ticket Town Championship clean or dirty","unlock":"champion cabinet, tournaments, and prize discounts","category":"activities","tags":["arcade","competition","repair"]},
  {"id":"grand-aurora-hotel","name":"Grand Aurora Hotel","districtId":"grand-hotel-row","leadNpcId":"nora-bright","leadNpcName":"Nora Bright","leadRole":"hotel manager","personality":"high-energy-exacting","premise":"Hospitality work grows from bellhop and housekeeping to concierge decisions, major events, and managing guest crises.","skill":"hospitality management","coreTask":"complete service shifts and solve guest requests","complication":"a celebrity guest asks staff to hide damage and blame a worker","routeA":"protect the worker and charge the guest","routeB":"protect the guest for Starline connections","finale":"manage a sold-out festival weekend","unlock":"hotel management and residence discounts","category":"career","tags":["hotel","service","events"]},
  {"id":"strip-showhouse-production","name":"Strip Showhouse Production","districtId":"show-district","leadNpcId":"desmond-flare","leadNpcName":"Desmond Flare","leadRole":"show producer","personality":"dramatic-disciplined","premise":"The player learns cues, illusions, rehearsals, safety, ticketing, and the difference between spectacle and deception.","skill":"stage production","coreTask":"run cues and repair show equipment","complication":"a star performer demands an unsafe effect","routeA":"redesign the show safely","routeB":"run the effect for a career-making performance","finale":"open the Strip's largest original show","unlock":"show production career and performance access","category":"career","tags":["performance","stage","safety"]},
  {"id":"eye-in-the-sky","name":"Eye in the Sky","districtId":"service-quarter","leadNpcId":"captain-rene-fox","leadNpcName":"Captain Rene Fox","leadRole":"casino security chief","personality":"sharp-unflappable","premise":"Security gameplay focuses on cameras, pattern recognition, de-escalation, lost children, theft, and cheating investigations.","skill":"security observation","coreTask":"monitor floors and respond to incidents","complication":"evidence shows security staff are planting accusations","routeA":"expose the corruption","routeB":"use the scheme to control problem guests","finale":"resolve a citywide coordinated cheating ring","unlock":"casino security career and operations access","category":"career","tags":["security","investigation","ethics"]},
  {"id":"brighthouse-probability-lab","name":"BrightHouse Probability Lab","districtId":"civic-academy","leadNpcId":"professor-lina-odds","leadNpcName":"Professor Lina Odds","leadRole":"probability teacher","personality":"witty-rigorous","premise":"The academy teaches odds, budgeting, risk, game design, and how to recognize manipulative systems.","skill":"math and budgeting","coreTask":"complete lessons and design fair games","complication":"a sponsor rejects a student game because it pays out too fairly","routeA":"publish the fair design independently","routeB":"alter the game for commercial approval","finale":"win the educational game showcase","unlock":"probability certification and game-design contracts","category":"career","tags":["school","math","design"]},
  {"id":"neon-plaza-festival","name":"Neon Plaza Festival","districtId":"neon-plaza","leadNpcId":"tasha-sparks","leadNpcName":"Tasha Sparks","leadRole":"festival coordinator","personality":"bright-commanding","premise":"A city festival links performers, vendors, hotels, transit, security, weather, and neighborhood access.","skill":"event coordination","coreTask":"book acts and organize vendors","complication":"premium sponsors demand the public plaza be fenced off","routeA":"keep the festival public","routeB":"accept exclusive zones for a larger budget","finale":"deliver a safe multi-district festival night","unlock":"festival events and citywide reputation","category":"story","tags":["festival","community","logistics"]},
  {"id":"service-quarter-backstage","name":"Service Quarter Backstage","districtId":"service-quarter","leadNpcId":"miguel-ortiz","leadNpcName":"Miguel Ortiz","leadRole":"operations foreman","personality":"practical-dry","premise":"Behind the lights are laundry, food distribution, sign repair, sanitation, delivery, and power crews.","skill":"operations","coreTask":"complete backstage service routes","complication":"management hides dangerous maintenance delays before an inspection","routeA":"report the delays and fix them","routeB":"help stage a clean inspection for a payout","finale":"keep the Strip running during a major outage","unlock":"operations career and service shortcuts","category":"career","tags":["labor","maintenance","city-systems"]},
  {"id":"high-roller-reputation","name":"High Roller Reputation","districtId":"neon-plaza","leadNpcId":"cassian-royal","leadNpcName":"Cassian Royal","leadRole":"VIP host","personality":"smooth-calculating","premise":"The player can build status through tournaments, fashion, hospitality relationships, and controlled spending without real-money systems.","skill":"social strategy","coreTask":"complete VIP events and reputation challenges","complication":"the host offers manipulated advantages against another player","routeA":"refuse and build authentic status","routeB":"accept and enter the rigged social circuit","finale":"survive a public reputation showdown","unlock":"VIP access or underground influence route","category":"people","tags":["status","choices","reputation"]},
  {"id":"know-when-to-walk","name":"Know When to Walk","districtId":"residential-blocks","leadNpcId":"dr-melody-grant","leadNpcName":"Dr. Melody Grant","leadRole":"youth counselor","personality":"calm-kind","premise":"A recovery and responsibility storyline helps NPCs and players recognize unhealthy risk patterns, debt pressure, and manipulation.","skill":"support and budgeting","coreTask":"help residents create limits and alternatives","complication":"a game hall quietly targets a vulnerable regular","routeA":"document the targeting and force policy changes","routeB":"take a settlement and keep the practice hidden","finale":"launch a citywide responsible-play program","unlock":"counseling support, budgeting tools, and policy changes","category":"people","tags":["wellbeing","budgeting","ethics"]}
],
  supportNpcs: [
  {"id":"jules-home","name":"Jules Home","districtId":"residential-blocks","role":"resident association lead","personality":"friendly-sharp","goal":"keep residents from being ignored","fear":"another hotel expansion","secret":"tracks noise complaints by song tempo","value":"community","petPeeve":"tourists who think workers teleport home"},
  {"id":"penny-prize","name":"Penny Prize","districtId":"arcade-district","role":"prize counter clerk","personality":"bubbly-skeptical","goal":"make rewards fair","fear":"rigged redemption rates","secret":"can identify every cabinet by its attract sound","value":"fair play","petPeeve":"sticky tickets"}
],
});

export default CASINO_STRIP_STORY_PACK;
