import { makeStoryPack } from '../storyFactory.js';

export const DUNGEON_OUTSKIRTS_STORY_PACK = makeStoryPack({
  townId: "dungeon-outskirts",
  label: "Dungeon Outskirts",
  baseMoney: 600,
  arcs: [
  {"id":"adventurer-academy-certification","name":"Adventurer Academy Certification","districtId":"guild-academy","leadNpcId":"elder-wyn","leadNpcName":"Elder Wyn","leadRole":"guild elder","personality":"gentle-serious","premise":"The player learns combat, survival, appraisal, maps, return rules, and support roles before deeper floors.","skill":"dungeon preparation","coreTask":"complete academy certifications","complication":"a talented student refuses safety rules and disappears below","routeA":"organize a sanctioned rescue","routeB":"follow secretly for faster access","finale":"return with the student and proof of readiness","unlock":"deeper-floor permits and class specialization","category":"career","tags":["school","dungeon","safety"]},
  {"id":"old-stone-halls","name":"Old Stone Halls","districtId":"dungeon-floor-1-5","leadNpcId":"mara-stone","leadNpcName":"Mara Stone","leadRole":"ruin cartographer","personality":"focused-curious","premise":"The beginner floor arc introduces authored rooms, keys, traps, shrines, rescues, and the first Gatekeeper.","skill":"exploration and mapping","coreTask":"map rooms and recover lost markers","complication":"a shortcut map may have been planted to trap beginners","routeA":"warn the guild and trace the saboteur","routeB":"use the shortcut for rare loot","finale":"defeat or outsmart the Gatekeeper","unlock":"reliable floor maps and first relic tier","category":"story","tags":["dungeon","mapping","boss"]},
  {"id":"root-caverns","name":"Root Caverns","districtId":"dungeon-floor-6-10","leadNpcId":"sage-greenbriar","leadNpcName":"Sage Greenbriar","leadRole":"potion botanist","personality":"earthy-sharp","premise":"The caverns mix natural hazards, ingredients, pet passages, fungal ecology, and the Root Guardian.","skill":"survival and ingredients","coreTask":"collect plants and navigate living tunnels","complication":"harvesting too much begins destabilizing the cavern","routeA":"limit collection and restore the habitat","routeB":"strip the rare ingredients before access closes","finale":"calm or defeat the Root Guardian","unlock":"advanced potions and pet routes","category":"story","tags":["dungeon","ecology","crafting"]},
  {"id":"forgotten-library","name":"Forgotten Library","districtId":"dungeon-floor-11-15","leadNpcId":"professor-nyla-page","leadNpcName":"Professor Nyla Page","leadRole":"rune scholar","personality":"brilliant-absent","premise":"A puzzle-heavy arc uses scripts, maps, memory rooms, false histories, and the Archivist.","skill":"runes and puzzles","coreTask":"translate texts and solve sequence rooms","complication":"a recovered history could destroy the guild's founding myth","routeA":"publish the truth","routeB":"hide the pages to preserve unity","finale":"confront the Archivist and secure the archive","unlock":"rune skills and appraisal mastery","category":"story","tags":["dungeon","lore","puzzles"]},
  {"id":"crystal-depths","name":"Crystal Depths","districtId":"dungeon-floor-16-20","leadNpcId":"zuri-glass","leadNpcName":"Zuri Glass","leadRole":"crystal appraiser","personality":"cool-intense","premise":"Reflection puzzles, rare gems, unstable chambers, and competing treasure crews define the Crystal Depths.","skill":"appraisal and navigation","coreTask":"identify crystals and stabilize rooms","complication":"another crew is trapped after ignoring warnings","routeA":"sacrifice the best claim to rescue them","routeB":"take the claim and leave rescue to wardens","finale":"defeat the Crystal Colossus","unlock":"premium relic tier and crystal crafting","category":"story","tags":["dungeon","treasure","rescue"]},
  {"id":"forge-chasm","name":"Forge Chasm","districtId":"deep-dungeon","leadNpcId":"borin-ironroot","leadNpcName":"Borin Ironroot","leadRole":"blacksmith","personality":"blunt-loyal","premise":"Mechanical traps, heat routes, ancient machines, and forge materials connect the dungeon to surface crafting.","skill":"forging and mechanics","coreTask":"recover materials and repair mechanisms","complication":"activating the ancient forge may wake the whole chasm","routeA":"stabilize it for community crafting","routeB":"overcharge it for exclusive gear","finale":"survive the Forge Heart sequence","unlock":"master forging and legendary upgrades","category":"career","tags":["dungeon","forge","mechanics"]},
  {"id":"warden-rescue-corps","name":"Warden Rescue Corps","districtId":"warden-watch","leadNpcId":"warden-akeem","leadNpcName":"Warden Akeem","leadRole":"warden","personality":"measured-protective","premise":"A career arc covers permits, missing parties, sealed zones, illegal relics, and difficult rescue decisions.","skill":"rescue and law","coreTask":"train with wardens and answer calls","complication":"a politically connected explorer is trapped in a sealed floor after bribing staff","routeA":"rescue everyone and expose the bribery","routeB":"prioritize the explorer and protect the office","finale":"coordinate a multi-floor collapse rescue","unlock":"warden rank progression and restricted permits","category":"career","tags":["rescue","law","dungeon"]},
  {"id":"relic-smugglers","name":"Relic Smugglers","districtId":"outpost-commons","leadNpcId":"nyx-vellum","leadNpcName":"Nyx Vellum","leadRole":"relic broker","personality":"soft-spoken-dangerous","premise":"A branching underground arc deals in cursed items, fake appraisals, hidden buyers, and consequences that follow the player to other towns.","skill":"appraisal and deception","coreTask":"move relics and identify buyers","complication":"one relic is actively harming whoever carries it","routeA":"turn it over to the shrine and expose the network","routeB":"deliver it for the largest payout","finale":"decide who controls the smuggling routes","unlock":"black-market relic access or reform path","category":"people","tags":["crime","relics","choices"]},
  {"id":"companion-bond","name":"Companion Bond","districtId":"outpost-commons","leadNpcId":"pippa-rune","leadNpcName":"Pippa Rune","leadRole":"companion trainer","personality":"sunny-firm","premise":"The player bonds with a helper creature through care, training, dungeon routes, fear, and trust.","skill":"pet care and teamwork","coreTask":"train and protect a companion","complication":"a breeder offers a stronger animal in exchange for abandoning the first","routeA":"stay loyal and develop unique abilities","routeB":"switch companions and gain immediate power with trust costs","finale":"complete a rescue only the bonded companion can solve","unlock":"companion housing, skills, and repeatable runs","category":"people","tags":["pets","relationship","dungeon"]},
  {"id":"royal-vault-endgame","name":"Royal Vault Endgame","districtId":"royal-vault","leadNpcId":"queen-echo","leadNpcName":"Queen Echo","leadRole":"vault guardian","personality":"regal-ambiguous","premise":"The dungeon's endgame arc asks whether the Royal Vault is treasure, prison, archive, or test.","skill":"endgame exploration","coreTask":"assemble keys from every floor family","complication":"the final relic offers power by rewriting one past consequence","routeA":"refuse the rewrite and preserve the player's history","routeB":"use the relic and accept a new hidden cost","finale":"complete the Royal Vault trial","unlock":"endless floors, legendary rewards, and world-state epilogue","category":"story","tags":["endgame","dungeon","consequence"]}
],
  supportNpcs: [
  {"id":"healer-ama","name":"Healer Ama","districtId":"shrine-court","role":"healer","personality":"gentle-firm","goal":"send people back prepared","fear":"losing someone to pride","secret":"remembers every injury and every excuse","value":"care","petPeeve":"adventurers calling bandages optional"},
  {"id":"tomas-pack","name":"Tomas Pack","districtId":"outpost-housing","role":"supply merchant","personality":"cautious-funny","goal":"stock useful gear instead of shiny junk","fear":"a blocked supply road","secret":"tests every rope himself","value":"preparedness","petPeeve":"people buying torches after entering the dark"}
],
});

export default DUNGEON_OUTSKIRTS_STORY_PACK;
