import { makeStoryPack } from '../storyFactory.js';

export const FISHING_HARBOR_STORY_PACK = makeStoryPack({
  townId: "fishing-harbor",
  label: "Fishing Harbor",
  baseMoney: 350,
  arcs: [
  {
    "id": "harbor-captain-certification",
    "name": "Harbor Captain Certification",
    "districtId": "harbor-center",
    "leadNpcId": "cap-odell",
    "leadNpcName": "Cap Odell",
    "leadRole": "harbor master",
    "personality": "weathered-gruff",
    "premise": "The player progresses from visitor permit to trusted captain through navigation, weather reading, rescue practice, and commercial responsibility.",
    "skill": "boating and navigation",
    "coreTask": "complete permit drills and captain real routes",
    "complication": "a charter owner pressures the player to ignore safety limits",
    "routeA": "cancel the unsafe trip and protect passengers",
    "routeB": "take the trip for a premium payout",
    "finale": "captain a storm evacuation route",
    "unlock": "captain license, larger boat rentals, and charter work",
    "category": "career",
    "tags": ["boats", "permits", "weather"]
  },
  {
    "id": "market-wharf-price-war",
    "name": "Market Wharf Price War",
    "districtId": "market-wharf",
    "leadNpcId": "sela-voss",
    "leadNpcName": "Sela Voss",
    "leadRole": "seafood vendor",
    "personality": "bargaining-bright",
    "premise": "Fish prices collapse after false contamination rumors and aggressive buying from an outside distributor.",
    "skill": "trading and quality control",
    "coreTask": "grade catches, negotiate prices, and verify supply records",
    "complication": "someone inside the wharf is feeding the distributor private data",
    "routeA": "build a transparent cooperative auction",
    "routeB": "secretly sell information for better margins",
    "finale": "restore the market during the annual seafood fair",
    "unlock": "dynamic market contracts and vendor discounts",
    "category": "career",
    "tags": ["market", "economy", "mystery"]
  },
  {
    "id": "marine-academy-research",
    "name": "Marine Academy Research",
    "districtId": "marine-academy",
    "leadNpcId": "dr-nia-current",
    "leadNpcName": "Dr. Nia Current",
    "leadRole": "marine scientist",
    "personality": "curious-direct",
    "premise": "A long research arc teaches fish identification, tides, tagging, sanctuary rules, and how discoveries create responsibilities.",
    "skill": "marine science",
    "coreTask": "collect samples and analyze migration patterns",
    "complication": "research data could expose a protected breeding ground to treasure hunters",
    "routeA": "publish safely and protect the location",
    "routeB": "sell the coordinates to fund the lab",
    "finale": "present the findings to the harbor council",
    "unlock": "marine research career and advanced ecology missions",
    "category": "career",
    "tags": ["science", "ecology", "school"]
  },
  {
    "id": "lighthouse-rescue-watch",
    "name": "Lighthouse Rescue Watch",
    "districtId": "lighthouse-point",
    "leadNpcId": "imani-reed",
    "leadNpcName": "Imani Reed",
    "leadRole": "lighthouse keeper",
    "personality": "quiet-alert",
    "premise": "The lighthouse crew handles fog signals, lost boats, cliff paths, and a mystery distress call that repeats on clear nights.",
    "skill": "rescue and signal work",
    "coreTask": "maintain the light and respond to coastal calls",
    "complication": "the repeating call is tied to an old wreck and a living smuggling route",
    "routeA": "report the route and rescue the trapped crew",
    "routeB": "use the route to access hidden salvage",
    "finale": "complete a multi-stage night rescue in heavy fog",
    "unlock": "lighthouse watch shifts and rare-water access",
    "category": "career",
    "tags": ["rescue", "mystery", "lighthouse"]
  },
  {
    "id": "anchor-and-axle-restoration",
    "name": "Anchor and Axle Restoration",
    "districtId": "boatworks-yard",
    "leadNpcId": "rafael-santos",
    "leadNpcName": "Rafael Santos",
    "leadRole": "boat mechanic",
    "personality": "patient-meticulous",
    "premise": "A historic workboat can become a museum piece, a commercial vessel, or a private speed build depending on the player's decisions.",
    "skill": "mechanics and restoration",
    "coreTask": "repair hull, engine, wiring, and navigation gear",
    "complication": "the original owner disputes who has the right to decide the boat's future",
    "routeA": "restore it for community use",
    "routeB": "convert it for profit and performance",
    "finale": "launch the finished vessel during Harbor Day",
    "unlock": "boat restoration shop access and custom parts",
    "category": "career",
    "tags": ["mechanics", "crafting", "history"]
  },
  {
    "id": "protected-waters-line",
    "name": "Protected Waters Line",
    "districtId": "lighthouse-point",
    "leadNpcId": "talia-brooks",
    "leadNpcName": "Talia Brooks",
    "leadRole": "wildlife officer",
    "personality": "serious-compassionate",
    "premise": "Protected waters create a branching path between conservation, regulated fishing, and illegal poaching.",
    "skill": "wildlife law",
    "coreTask": "patrol boundaries and identify protected species",
    "complication": "a popular fisher is secretly using banned equipment",
    "routeA": "enforce the rules despite public backlash",
    "routeB": "cover for the fisher and enter the poaching network",
    "finale": "stop a mass illegal catch during a tide event",
    "unlock": "sanctuary patrols or poacher contracts with consequences",
    "category": "career",
    "tags": ["law", "wildlife", "crime"]
  },
  {
    "id": "dockside-diner-family",
    "name": "Dockside Diner Family",
    "districtId": "dockside-village",
    "leadNpcId": "miss-pearl-jackson",
    "leadNpcName": "Miss Pearl Jackson",
    "leadRole": "diner owner",
    "personality": "warm-commanding",
    "premise": "The diner is a social hub dealing with family expectations, supply shortages, special orders, and the temptation to franchise away its identity.",
    "skill": "cooking and hospitality",
    "coreTask": "work kitchen and service shifts",
    "complication": "a corporate offer could save the building but erase the family menu",
    "routeA": "keep the diner independent through community support",
    "routeB": "take the franchise deal and modernize aggressively",
    "finale": "serve the biggest Harbor Day rush in town history",
    "unlock": "diner management, recipes, and catering jobs",
    "category": "career",
    "tags": ["food", "family", "business"]
  },
  {
    "id": "storm-season-command",
    "name": "Storm Season Command",
    "districtId": "harbor-center",
    "leadNpcId": "chief-eli-turner",
    "leadNpcName": "Chief Eli Turner",
    "leadRole": "harbor rescue chief",
    "personality": "calm-under-pressure",
    "premise": "A seasonal storm arc connects weather stations, evacuation, boat securing, clinic supplies, and post-storm rebuilding.",
    "skill": "emergency management",
    "coreTask": "prepare districts and run drills",
    "complication": "a developer refuses to evacuate a vulnerable luxury dock",
    "routeA": "enforce evacuation equally",
    "routeB": "prioritize the working harbor and leave the private dock to its owner",
    "finale": "coordinate the full storm response",
    "unlock": "emergency contracts and storm-event leadership",
    "category": "story",
    "tags": ["weather", "rescue", "town-event"]
  },
  {
    "id": "gillyfish-discovery-program",
    "name": "Gillyfish Discovery Program",
    "districtId": "lighthouse-trench",
    "leadNpcId": "niko-waves",
    "leadNpcName": "Niko Waves",
    "leadRole": "deep-water fisher",
    "personality": "superstitious-clever",
    "premise": "Beyond the mandatory Gillyfish unlock, this arc explores sightings, ethical handling, gifting, research, and the social consequences of permanent adaptation.",
    "skill": "deep fishing",
    "coreTask": "track rare-current conditions and eligible catches",
    "complication": "collectors begin paying children to monopolize the fishing nodes",
    "routeA": "create a fair community catch program",
    "routeB": "control the market and become the exclusive broker",
    "finale": "protect a spawning event at Lighthouse Trench",
    "unlock": "ethical rare-fish program or exclusive collector network",
    "category": "story",
    "tags": ["gillyfish", "aqualume", "fishing"]
  },
  {
    "id": "harbor-patrol-career",
    "name": "Harbor Patrol Career",
    "districtId": "harbor-center",
    "leadNpcId": "officer-lena-tide",
    "leadNpcName": "Officer Lena Tide",
    "leadRole": "harbor patrol officer",
    "personality": "direct-dry",
    "premise": "The player can join Harbor Patrol through boat handling, permit enforcement, rescue, evidence handling, and community judgment.",
    "skill": "water law and rescue",
    "coreTask": "complete patrol calls and inspections",
    "complication": "contraband evidence points toward a respected academy employee",
    "routeA": "follow the evidence and preserve due process",
    "routeB": "bury the evidence to protect the academy",
    "finale": "resolve a bridge-channel emergency without escalation",
    "unlock": "Harbor Patrol rank progression",
    "category": "career",
    "tags": ["police", "boats", "evidence"]
  }
],
  supportNpcs: [
  {
    "id": "bo-ice",
    "name": "Bo Ice",
    "districtId": "market-wharf",
    "role": "ice-house worker",
    "personality": "loud-helpful",
    "goal": "modernize the cold chain",
    "fear": "a market shutdown",
    "secret": "once lost a whole shipment by trusting a broken gauge",
    "value": "honest work",
    "petPeeve": "warm fish and warmer excuses"
  },
  {
    "id": "kendra-bay",
    "name": "Kendra Bay",
    "districtId": "dockside-village",
    "role": "clinic nurse",
    "personality": "calm-practical",
    "goal": "improve marine first aid",
    "fear": "another preventable rescue injury",
    "secret": "secretly studies navigation at night",
    "value": "care",
    "petPeeve": "people saying they are fine while dripping seawater"
  }
],
});

export default FISHING_HARBOR_STORY_PACK;
