import { makeStoryPack } from '../storyFactory.js';

export const OBBY_CANYON_STORY_PACK = makeStoryPack({
  townId: "obby-canyon",
  label: "Obby Canyon",
  baseMoney: 450,
  arcs: [
  {"id":"beginner-valley-confidence","name":"Beginner Valley Confidence","districtId":"beginner-valley","leadNpcId":"coach-tavi","leadNpcName":"Coach Tavi","leadRole":"movement coach","personality":"competitive-kind","premise":"The player learns jumping, checkpoints, resets, route reading, and how to help beginners without mocking failure.","skill":"movement fundamentals","coreTask":"complete beginner courses and coach new runners","complication":"a viral challenge encourages unsafe shortcuts","routeA":"teach safe mastery","routeB":"use the shortcut for attention","finale":"lead a community beginner race","unlock":"coach jobs and advanced course access","category":"activities","tags":["obby","training","community"]},
  {"id":"moving-towers-league","name":"Moving Towers League","districtId":"moving-towers","leadNpcId":"dante-shift","leadNpcName":"Dante Shift","leadRole":"tower competitor","personality":"cocky-generous","premise":"Rotating platforms, timed doors, elevators, and route choices create a competitive league.","skill":"timing and route memory","coreTask":"qualify through tower trials","complication":"a timing controller is being altered between runs","routeA":"pause the league and investigate","routeB":"exploit the altered timing to advance","finale":"win the tower finals under fair settings","unlock":"tower leagues and advanced time trials","category":"activities","tags":["obby","competition","mystery"]},
  {"id":"cliffside-rescue-route","name":"Cliffside Rescue Route","districtId":"cliffside-courses","leadNpcId":"ranger-sol","leadNpcName":"Ranger Sol","leadRole":"canyon ranger","personality":"alert-deadpan","premise":"The cliff routes combine balance, rope systems, rescues, weather, and route maintenance.","skill":"balance and rescue","coreTask":"patrol courses and recover stranded runners","complication":"a maintenance shortcut is causing repeated failures","routeA":"close the route and rebuild it","routeB":"keep it open to preserve event revenue","finale":"complete a high-wind rescue","unlock":"ranger jobs and cliff-route clearance","category":"career","tags":["obby","rescue","safety"]},
  {"id":"hazard-basin-control","name":"Hazard Basin Control","districtId":"hazard-basin","leadNpcId":"imani-flux","leadNpcName":"Imani Flux","leadRole":"hazard engineer","personality":"bold-technical","premise":"Stylized lava, disappearing platforms, emergency resets, and crowd spectacle require precise control.","skill":"hazard systems","coreTask":"test shutoffs and design safe sequences","complication":"a sponsor demands longer reset delays for drama","routeA":"protect instant recovery","routeB":"accept the spectacle design","finale":"run the Hazard Basin championship safely","unlock":"hazard course creation and engineering contracts","category":"career","tags":["obby","engineering","events"]},
  {"id":"skyrail-ridge-mastery","name":"Skyrail Ridge Mastery","districtId":"skyrail-ridge","leadNpcId":"kellan-wind","leadNpcName":"Kellan Wind","leadRole":"zipline guide","personality":"calm-thrillseeker","premise":"Ziplines, rings, wind reading, suspended bridges, and summit access define the canyon's premium route.","skill":"aerial movement","coreTask":"complete guided ridge routes","complication":"an incoming wind event traps guests at the summit","routeA":"cancel the record attempt and evacuate","routeB":"continue for the record before conditions worsen","finale":"complete the summit rescue and final ring route","unlock":"Skyrail certification and summit lodge access","category":"activities","tags":["obby","ziplines","weather"]},
  {"id":"momentum-academy-design","name":"Momentum Academy Design","districtId":"momentum-academy","leadNpcId":"professor-jules-arc","leadNpcName":"Professor Jules Arc","leadRole":"course design teacher","personality":"creative-demanding","premise":"Students learn readability, accessibility, checkpoint spacing, theme, difficulty, and playtesting.","skill":"game and course design","coreTask":"build and test course modules","complication":"a popular design is fun for experts but impossible for many players","routeA":"redesign for multiple routes","routeB":"keep the elite design and build a separate beginner course","finale":"publish an academy course used in the live canyon","unlock":"course designer career and creator tools","category":"career","tags":["school","design","accessibility"]},
  {"id":"canyon-rescue-corps","name":"Canyon Rescue Corps","districtId":"ranger-rescue","leadNpcId":"chief-naya-stone","leadNpcName":"Chief Naya Stone","leadRole":"rescue chief","personality":"steady-commanding","premise":"A full emergency career covers falls, equipment failure, heat, lost runners, and coordinated response.","skill":"rescue operations","coreTask":"complete drills and real calls","complication":"a famous competitor refuses medical clearance","routeA":"enforce the restriction","routeB":"let them compete and prepare a hidden rescue plan","finale":"manage a canyon-wide emergency event","unlock":"rescue rank progression","category":"career","tags":["rescue","career","ethics"]},
  {"id":"build-the-course","name":"Build the Course","districtId":"maintenance-yard","leadNpcId":"leo-bolts","leadNpcName":"Leo Bolts","leadRole":"maintenance lead","personality":"joking-meticulous","premise":"The player moves from repairs to building an entire playable course with budgets, parts, testing, and public feedback.","skill":"construction and maintenance","coreTask":"repair platforms and collect design materials","complication":"cheap parts would meet the deadline but fail long-term","routeA":"delay and build correctly","routeB":"use the cheap parts and patch problems later","finale":"open the completed community course","unlock":"course construction contracts and custom cosmetics","category":"career","tags":["construction","design","maintenance"]},
  {"id":"rival-league","name":"Rival League","districtId":"course-select-plaza","leadNpcId":"sasha-quick","leadNpcName":"Sasha Quick","leadRole":"rival runner","personality":"sharp-competitive","premise":"A relationship-heavy rivalry can become friendship, respectful competition, sabotage, or an underground challenge route.","skill":"competition and relationships","coreTask":"race Sasha through multiple course families","complication":"someone frames one runner for checkpoint tampering","routeA":"work together to expose the frame-up","routeB":"use the accusation to eliminate the rival","finale":"settle the rivalry in a multi-course final","unlock":"rival, friend, or underground league path","category":"people","tags":["rivalry","relationships","competition"]},
  {"id":"everybody-gets-a-route","name":"Everybody Gets a Route","districtId":"practice-park","leadNpcId":"mina-park","leadNpcName":"Mina Park","leadRole":"accessibility advocate","personality":"patient-inventive","premise":"The canyon develops alternate routes, visual cues, reduced-motion options, and spectator access without making mastery meaningless.","skill":"accessible design","coreTask":"test routes with different players","complication":"traditionalists claim accessibility ruins competition","routeA":"prove multiple routes can share fair scoring","routeB":"split the canyon into separate leagues","finale":"launch the inclusive Canyon Games","unlock":"accessibility settings, adaptive courses, and civic reputation","category":"story","tags":["accessibility","community","design"]}
],
  supportNpcs: [
  {"id":"drea-balance","name":"Drea Balance","districtId":"practice-park","role":"physical therapist","personality":"patient-direct","goal":"help players recover confidence","fear":"someone hiding an injury","secret":"designs low-impact training routes","value":"sustainable progress","petPeeve":"runners treating pain like a scoreboard"},
  {"id":"omar-cheer","name":"Omar Cheer","districtId":"base-camp","role":"event announcer","personality":"big-hearted-loud","goal":"make every finish feel earned","fear":"the crowd turning cruel","secret":"practices names so he never embarrasses a runner","value":"encouragement","petPeeve":"booing beginners"}
],
});

export default OBBY_CANYON_STORY_PACK;
