import { makeStoryPack } from '../storyFactory.js';

export const RICH_HILLS_STORY_PACK = makeStoryPack({
  townId: "rich-hills",
  label: "Rich Hills",
  baseMoney: 500,
  arcs: [
  {"id":"golden-key-property-ladder","name":"Golden Key Property Ladder","districtId":"luxury-row","leadNpcId":"celeste-crown","leadNpcName":"Celeste Crown","leadRole":"property broker","personality":"polished-candid","premise":"The player learns rentals, mortgages, repairs, inspections, tenant rights, negotiation, and responsible property ownership.","skill":"property and negotiation","coreTask":"show homes, review costs, and manage repairs","complication":"an estate sale hides serious damage and a displaced tenant","routeA":"disclose the truth and protect the tenant","routeB":"close the sale quietly for a major commission","finale":"complete a fair multi-property redevelopment deal","unlock":"property career and advanced ownership options","category":"career","tags":["property","finance","ethics"],"homeTownId":"rich-hills"},
  {"id":"crown-greens-hospitality","name":"Crown Greens Hospitality","districtId":"country-club","leadNpcId":"aisha-monroe","leadNpcName":"Aisha Monroe","leadRole":"club director","personality":"polished-warm","premise":"Country club work includes caddying, events, service recovery, networking, and challenging the assumption that only wealthy residents belong.","skill":"hospitality and golf","coreTask":"serve events and train on the course","complication":"members attempt to block a public youth tournament","routeA":"open the event to the wider city","routeB":"preserve exclusivity for higher status rewards","finale":"run the Crown Greens Invitational","unlock":"club management and golf events","category":"career","tags":["hospitality","golf","status"]},
  {"id":"estate-ridge-security","name":"Estate Ridge Security","districtId":"estate-ridge","leadNpcId":"marcus-vale","leadNpcName":"Marcus Vale","leadRole":"security chief","personality":"formal-fair","premise":"The player learns gates, warnings, privacy, emergency response, and the danger of treating every outsider as a threat.","skill":"security and de-escalation","coreTask":"patrol estates and verify incidents","complication":"a wealthy resident demands an innocent worker be banned","routeA":"challenge the resident and protect the worker","routeB":"enforce the ban to preserve elite trust","finale":"stop a real break-in without punishing the wrong people","unlock":"security career and estate clearance","category":"career","tags":["security","class","ethics"]},
  {"id":"crownline-motors-legacy","name":"Crownline Motors Legacy","districtId":"luxury-row","leadNpcId":"malcolm-crown","leadNpcName":"Malcolm Crown","leadRole":"dealership owner","personality":"charismatic-demanding","premise":"A luxury dealership arc covers sales, detailing, test drives, financing lessons, collector events, and a disputed classic car.","skill":"vehicles and sales","coreTask":"sell and service premium cars","complication":"the dealership discovers a vehicle with falsified ownership records","routeA":"return the vehicle and expose the broker","routeB":"hide the paperwork and secure the sale","finale":"host the Crownline Concours with the brand's future at stake","unlock":"luxury dealership career and collector access","category":"career","tags":["cars","sales","investigation"]},
  {"id":"garden-commons-coalition","name":"Garden Commons Coalition","districtId":"garden-commons","leadNpcId":"luz-martinez","leadNpcName":"Luz Martinez","leadRole":"community organizer","personality":"bright-persistent","premise":"Garden Commons becomes the meeting point between wealthy residents, service workers, students, and families.","skill":"community organizing","coreTask":"run markets, cleanups, and public meetings","complication":"a proposal would privatize the park for exclusive events","routeA":"defend public access","routeB":"support private management for better funding","finale":"deliver the largest public festival in Rich Hills","unlock":"community events and coalition reputation","category":"town","tags":["community","public-space","politics"]},
  {"id":"legacy-academy-finance","name":"Legacy Academy Finance","districtId":"civic-crest","leadNpcId":"dr-jamal-price","leadNpcName":"Dr. Jamal Price","leadRole":"finance teacher","personality":"patient-precise","premise":"The player learns budgeting, credit, contracts, investments, business math, and how financial systems can help or trap people.","skill":"finance and education","coreTask":"complete lessons and help classmates","complication":"a school investment contest rewards a harmful business","routeA":"challenge the rules and build an ethical portfolio","routeB":"play to win and take the status prize","finale":"present a real community business plan","unlock":"finance certification and investment activities","category":"career","tags":["school","finance","business"]},
  {"id":"summit-yacht-club","name":"Summit Yacht Club","districtId":"marina-boulevard","leadNpcId":"captain-reese-hale","leadNpcName":"Captain Reese Hale","leadRole":"yacht captain","personality":"confident-responsible","premise":"The player moves from dockhand work to yacht navigation, guest management, racing, maintenance, and ownership readiness.","skill":"luxury boating","coreTask":"handle docks, guests, routes, and repairs","complication":"a high-status guest orders the player into restricted water","routeA":"refuse and protect the marina license","routeB":"comply for the relationship and risk enforcement","finale":"win the Summit Yacht Run safely","unlock":"yacht privileges, ownership path, and marina contracts","category":"career","tags":["boats","status","ownership"]},
  {"id":"service-village-solidarity","name":"Service Village Solidarity","districtId":"service-village","leadNpcId":"keisha-long","leadNpcName":"Keisha Long","leadRole":"service depot supervisor","personality":"practical-bold","premise":"The workers who keep Rich Hills running organize around schedules, housing, respect, and fair access to town services.","skill":"operations and labor","coreTask":"complete landscaping, delivery, repair, and sanitation contracts","complication":"a contractor steals wages and threatens workers","routeA":"build a documented case and recover the money","routeB":"take a private payoff and leave the system intact","finale":"keep Rich Hills functioning during a worker walkout","unlock":"service management and worker trust","category":"career","tags":["labor","community","jobs"]},
  {"id":"gallery-crown-authenticity","name":"Gallery Crown Authenticity","districtId":"luxury-row","leadNpcId":"serena-kim","leadNpcName":"Serena Kim","leadRole":"art appraiser","personality":"elegant-skeptical","premise":"Art appraisal, auctions, provenance, and counterfeit detection turn Gallery Crown into a social mystery route.","skill":"appraisal and investigation","coreTask":"research artists and inspect objects","complication":"a counterfeit is tied to a charity auction and a powerful donor","routeA":"expose it before the auction","routeB":"quietly replace it and protect the event","finale":"identify the mastermind during the live sale","unlock":"appraisal career and rare collection access","category":"people","tags":["art","mystery","status"]},
  {"id":"wealth-with-purpose","name":"Wealth With Purpose","districtId":"garden-commons","leadNpcId":"omar-bennett","leadNpcName":"Omar Bennett","leadRole":"foundation director","personality":"thoughtful-cautious","premise":"The player decides whether wealth progression becomes philanthropy, influence, image management, or community investment.","skill":"strategy and ethics","coreTask":"evaluate projects and distribute grants","complication":"a headline donation hides harmful conditions","routeA":"redirect the money to resident-led projects","routeB":"accept the deal and gain elite influence","finale":"build a cross-district fund with measurable results","unlock":"foundation board, prestige, and community investment","category":"story","tags":["wealth","ethics","community"]}
],
  supportNpcs: [
  {"id":"nia-long","name":"Nia Longfield","districtId":"worker-housing","role":"apartment manager","personality":"direct-kind","goal":"keep worker housing affordable","fear":"a luxury conversion","secret":"has copies of every maintenance complaint","value":"stability","petPeeve":"owners calling mold a cosmetic issue"},
  {"id":"theo-green","name":"Theo Green","districtId":"country-club","role":"groundskeeper","personality":"quiet-witty","goal":"protect the course ecology","fear":"chemical runoff","secret":"knows every hidden path across the club","value":"stewardship","petPeeve":"people who think grass grows because it respects money"}
],
});

export default RICH_HILLS_STORY_PACK;
