import { makeStoryPack } from '../storyFactory.js';

export const STARTER_TOWN_STORY_PACK = makeStoryPack({
  townId: "starter-town",
  label: "Starter Town",
  baseMoney: 200,
  arcs: [
  {
    "id": "dreamdrop-neighborhood-network",
    "name": "Dreamdrop Neighborhood Network",
    "districtId": "dreamdrop-district",
    "leadNpcId": "ms-janice",
    "leadNpcName": "Ms. Janice",
    "leadRole": "neighborhood historian",
    "personality": "warm-nosy",
    "premise": "Old Dreamdrop is changing faster than its residents can agree on. The player helps neighbors document what matters, solve daily disputes, and decide which traditions deserve protection.",
    "skill": "community listening",
    "coreTask": "mediate neighbor errands and preserve local landmarks",
    "complication": "a redevelopment notice divides the block",
    "routeA": "organize residents to protect the old community spaces",
    "routeB": "negotiate upgrades that keep residents in place",
    "finale": "host a neighborhood assembly where every promise is tested",
    "unlock": "Dreamdrop community board contracts",
    "category": "town",
    "tags": ["community", "housing", "history"]
  },
  {
    "id": "zaylins-prep-student-council",
    "name": "Zaylins Prep Student Council",
    "districtId": "scholars-quarter",
    "leadNpcId": "principal-amara-cole",
    "leadNpcName": "Principal Amara Cole",
    "leadRole": "school principal",
    "personality": "firm-encouraging",
    "premise": "The school needs a student voice that can handle real budgets, rival clubs, attendance problems, and a campus event without turning every disagreement into a hallway war.",
    "skill": "leadership and academics",
    "coreTask": "run school projects and represent student concerns",
    "complication": "the election is poisoned by rumors and stolen campaign supplies",
    "routeA": "win honestly and expose the sabotage",
    "routeB": "use the scandal strategically to secure control",
    "finale": "deliver a citywide school showcase",
    "unlock": "student council office and advanced school events",
    "category": "career",
    "tags": ["school", "leadership", "reputation"]
  },
  {
    "id": "iron-city-championship",
    "name": "Iron City Championship",
    "districtId": "parkside-commons",
    "leadNpcId": "coach-rell",
    "leadNpcName": "Coach Rell",
    "leadRole": "gym trainer",
    "personality": "dry-gruff",
    "premise": "Coach Rell prepares the player for a city fitness tournament that rewards discipline, teamwork, and knowing when not to show off.",
    "skill": "fitness and discipline",
    "coreTask": "complete training blocks and coach younger members",
    "complication": "a rival gym offers shortcuts and performance scams",
    "routeA": "reject the shortcuts and train the whole team",
    "routeB": "use the rival's tactics and accept the reputation risk",
    "finale": "compete in the Iron City Championship",
    "unlock": "advanced training, coaching jobs, and tournament repeatables",
    "category": "activities",
    "tags": ["fitness", "competition", "mentoring"]
  },
  {
    "id": "market-mile-retail-war",
    "name": "Market Mile Retail War",
    "districtId": "market-mile",
    "leadNpcId": "maya-brooks",
    "leadNpcName": "Maya Brooks",
    "leadRole": "retail clerk",
    "personality": "quick-cheery",
    "premise": "Two shopping blocks compete for customers while delivery errors, fake reviews, and a predatory landlord threaten the smaller stores.",
    "skill": "sales and logistics",
    "coreTask": "manage stock, deliveries, and customer disputes",
    "complication": "evidence suggests one merchant is sabotaging the others",
    "routeA": "build a cooperative market association",
    "routeB": "help one store dominate and accept the fallout",
    "finale": "save Market Mile during its biggest shopping weekend",
    "unlock": "retail manager jobs and cooperative discounts",
    "category": "career",
    "tags": ["retail", "business", "logistics"]
  },
  {
    "id": "dreamdrop-police-academy",
    "name": "Dreamdrop Police Academy",
    "districtId": "civic-heights",
    "leadNpcId": "officer-dane",
    "leadNpcName": "Officer Dane",
    "leadRole": "police officer",
    "personality": "calm-wry",
    "premise": "The player learns law, de-escalation, evidence rules, and the difference between protecting a community and simply chasing people through it.",
    "skill": "law and judgment",
    "coreTask": "complete academy scenarios and community patrols",
    "complication": "a respected officer mishandles evidence in a politically sensitive case",
    "routeA": "report the misconduct and protect the case",
    "routeB": "hide the mistake to preserve the department's image",
    "finale": "resolve a hostage-free civic crisis through judgment",
    "unlock": "Dreamdrop police career or civilian safety liaison route",
    "category": "career",
    "tags": ["law", "career", "ethics"]
  },
  {
    "id": "worktower-career-ladder",
    "name": "WorkTower Career Ladder",
    "districtId": "commerce-row",
    "leadNpcId": "darius-king",
    "leadNpcName": "Darius King",
    "leadRole": "operations manager",
    "personality": "focused-fair",
    "premise": "WorkTower offers a believable climb from temporary shifts to project ownership, office politics, training, and management.",
    "skill": "work reliability and management",
    "coreTask": "complete office contracts and improve broken processes",
    "complication": "a supervisor takes credit for the player's work and blames juniors for failures",
    "routeA": "document the truth and protect the team",
    "routeB": "outmaneuver the supervisor and claim the promotion",
    "finale": "lead the building through a major systems outage",
    "unlock": "management track and business contacts",
    "category": "career",
    "tags": ["jobs", "management", "office"]
  },
  {
    "id": "willowbend-neighborhood-watch",
    "name": "Willowbend Neighborhood Watch",
    "districtId": "willowbend-residential",
    "leadNpcId": "ronnie-fields",
    "leadNpcName": "Ronnie Fields",
    "leadRole": "community coordinator",
    "personality": "protective-funny",
    "premise": "A string of package thefts and vandalism pushes Willowbend toward paranoia. The player must create safety without turning neighbors against one another.",
    "skill": "observation and trust",
    "coreTask": "check cameras, deliver packages, and interview residents",
    "complication": "the obvious suspect is innocent and the real culprit is connected to a local business",
    "routeA": "prove the truth without humiliating the wrong person",
    "routeB": "use the suspicion to secure control of the watch",
    "finale": "stop the real theft ring during a neighborhood event",
    "unlock": "neighborhood watch shifts and resident trust bonuses",
    "category": "town",
    "tags": ["community", "mystery", "safety"]
  },
  {
    "id": "parkside-sports-league",
    "name": "Parkside Sports League",
    "districtId": "parkside-commons",
    "leadNpcId": "kiara-banks",
    "leadNpcName": "Kiara Banks",
    "leadRole": "recreation director",
    "personality": "energetic-practical",
    "premise": "Parkside needs a youth league that can survive damaged equipment, clashing parents, rival teams, and a championship schedule.",
    "skill": "teamwork and sports",
    "coreTask": "coach drills, repair equipment, and schedule matches",
    "complication": "a sponsor demands unfair control over the league",
    "routeA": "keep the league community-run",
    "routeB": "take the money and accept sponsor rules",
    "finale": "win or host the Parkside Cup with the league intact",
    "unlock": "sports jobs, team cosmetics, and seasonal leagues",
    "category": "activities",
    "tags": ["sports", "teamwork", "events"]
  },
  {
    "id": "frostbox-custom-legacy",
    "name": "Frostbox Custom Legacy",
    "districtId": "dreamdrop-district",
    "leadNpcId": "malik-frost",
    "leadNpcName": "Malik Frost",
    "leadRole": "jeweler",
    "personality": "smooth-observant",
    "premise": "Malik wants Frostbox to become more than a flashy store by building a trusted custom business with traceable gems, apprentices, and signature designs.",
    "skill": "craft and appraisal",
    "coreTask": "source gems, design pieces, and handle clients",
    "complication": "a rare stone may be stolen property tied to a wealthy buyer",
    "routeA": "return the stone and rebuild the commission honestly",
    "routeB": "keep the sale and enter the gray-market jewelry route",
    "finale": "unveil a city signature piece at a public showcase",
    "unlock": "advanced jewelry crafting and custom commissions",
    "category": "career",
    "tags": ["crafting", "business", "ethics"]
  },
  {
    "id": "street-route-and-reform",
    "name": "Street Route and Reform",
    "districtId": "industrial-edge",
    "leadNpcId": "trey-maddox",
    "leadNpcName": "Trey Maddox",
    "leadRole": "street organizer",
    "personality": "charming-guarded",
    "premise": "The player can enter a kid-safe street hustle route involving stolen goods, risky deliveries, local influence, and a real path back out.",
    "skill": "risk assessment",
    "coreTask": "run favors and learn hidden networks",
    "complication": "a job targets someone the player personally knows",
    "routeA": "walk away, expose the setup, and begin reform",
    "routeB": "finish the job and gain underground standing",
    "finale": "survive the crew split without forcing violence",
    "unlock": "street contacts, reform services, or underground contracts based on choice",
    "category": "people",
    "tags": ["crime", "reform", "relationships"]
  }
],
  supportNpcs: [
  {
    "id": "lena-price",
    "name": "Lena Price",
    "districtId": "dreamdrop-district",
    "role": "corner-store owner",
    "personality": "warm-observant",
    "goal": "keep small businesses alive",
    "fear": "being priced out",
    "secret": "keeps a ledger of every neighborhood favor",
    "value": "fairness",
    "petPeeve": "people touching refrigerated drinks and walking away"
  },
  {
    "id": "jay-morris",
    "name": "Jay Morris",
    "districtId": "commerce-row",
    "role": "bus driver",
    "personality": "dry-friendly",
    "goal": "make every district reachable",
    "fear": "a major route cut",
    "secret": "knows who gets on where but never repeats private business",
    "value": "reliability",
    "petPeeve": "people asking if the bus goes somewhere while standing under the route map"
  }
],
});

export default STARTER_TOWN_STORY_PACK;
