import { makeStoryPack } from '../storyFactory.js';

export const STARLINE_CITY_STORY_PACK = makeStoryPack({
  townId: "starline-city",
  label: "Starline City",
  baseMoney: 550,
  arcs: [
  {"id":"unknown-to-headliner","name":"Unknown to Headliner","districtId":"premiere-boulevard","leadNpcId":"lana-starr","leadNpcName":"Lana Starr","leadRole":"talent agent","personality":"cool-demanding","premise":"The player progresses from background work through auditions, contracts, public appearances, difficult notes, and a headline opportunity.","skill":"acting and reputation","coreTask":"complete extra work and auditions","complication":"a role requires publicly humiliating another performer","routeA":"refuse and build a slower career","routeB":"take the role and absorb the reputation cost","finale":"headline the Red Carpet Theater","unlock":"acting career, representation, and premiere events","category":"career","tags":["acting","fame","ethics"],"homeTownId":"starline-city"},
  {"id":"rhythm-row-recording","name":"Rhythm Row Recording","districtId":"rhythm-row","leadNpcId":"jaylen-notes","leadNpcName":"Jaylen Notes","leadRole":"music producer","personality":"creative-blunt","premise":"The player writes, records, rehearses, mixes, performs, and negotiates ownership of an original song.","skill":"music production","coreTask":"complete rhythm and studio sessions","complication":"a label offers promotion in exchange for owning the song forever","routeA":"stay independent","routeB":"take the deal for rapid fame","finale":"perform the finished track at Encore Music Hall","unlock":"music career and recording studio access","category":"career","tags":["music","business","performance"]},
  {"id":"dance-floor-to-stage","name":"Dance Floor to Stage","districtId":"rhythm-row","leadNpcId":"naomi-step","leadNpcName":"Naomi Step","leadRole":"choreographer","personality":"intense-supportive","premise":"A dance arc covers practice, crews, choreography, injuries, auditions, and performance chemistry.","skill":"dance and teamwork","coreTask":"learn routines and lead rehearsals","complication":"a teammate hides an injury to avoid losing the spotlight","routeA":"protect them and rework the routine","routeB":"keep the original routine and risk the team","finale":"deliver the city showcase performance","unlock":"dance career and choreography jobs","category":"career","tags":["dance","teamwork","performance"]},
  {"id":"glam-quarter-house","name":"Glam Quarter House","districtId":"glam-quarter","leadNpcId":"aya-lux","leadNpcName":"Aya Lux","leadRole":"stylist","personality":"bold-honest","premise":"Fashion, hair, makeup, costume, photography, and identity combine in a route about style as craft rather than empty status.","skill":"styling and design","coreTask":"complete client looks and runway tasks","complication":"a major client demands copying a smaller designer","routeA":"credit and collaborate with the designer","routeB":"copy the look and secure the client","finale":"produce an original runway event","unlock":"stylist career, fashion line, and studio tools","category":"career","tags":["fashion","craft","reputation"]},
  {"id":"backlot-clockwork","name":"Backlot Clockwork","districtId":"backlot","leadNpcId":"devon-cue","leadNpcName":"Devon Cue","leadRole":"stage manager","personality":"tired-funny","premise":"Production jobs connect props, costumes, lights, sound, catering, vehicles, and every person who makes the illusion work.","skill":"production management","coreTask":"complete crew shifts and cue sequences","complication":"a producer cuts safety time to save money","routeA":"stop production and protect the crew","routeB":"push through for career credit","finale":"deliver a complex live production","unlock":"stage management career and studio clearance","category":"career","tags":["production","labor","safety"]},
  {"id":"contract-in-fine-print","name":"Contract in the Fine Print","districtId":"premiere-boulevard","leadNpcId":"veronica-chase","leadNpcName":"Veronica Chase","leadRole":"entertainment lawyer","personality":"precise-protective","premise":"The player learns contracts, representation, image rights, exclusivity, payment, and how exciting opportunities can become traps.","skill":"contract literacy","coreTask":"review deals and help performers","complication":"a dream contract hides a long-term ownership clause","routeA":"walk away and expose the clause","routeB":"sign for immediate access and accept restrictions","finale":"renegotiate a city-changing deal","unlock":"legal consulting, better contracts, and career protection","category":"people","tags":["contracts","law","fame"]},
  {"id":"public-image-crisis","name":"Public Image Crisis","districtId":"premiere-plaza","leadNpcId":"amira-press","leadNpcName":"Amira Press","leadRole":"publicist","personality":"quick-strategic","premise":"Rumors, mistakes, leaked footage, apologies, interviews, and public trust form a consequence-heavy reputation arc.","skill":"communication","coreTask":"handle interviews and verify rumors","complication":"the easiest recovery plan blames an innocent assistant","routeA":"take responsibility and rebuild slowly","routeB":"use the assistant as the shield","finale":"survive a live press event with the truth exposed","unlock":"publicist career and reputation recovery tools","category":"people","tags":["reputation","media","choices"]},
  {"id":"backlot-commons-stories","name":"Backlot Commons Stories","districtId":"backlot-commons","leadNpcId":"missy-wells","leadNpcName":"Missy Wells","leadRole":"community center director","personality":"warm-tough","premise":"Ordinary residents navigate rent, daycare, transit, production noise, jobs, and the city's obsession with fame.","skill":"community service","coreTask":"help residents and organize meetings","complication":"a studio expansion threatens affordable homes","routeA":"fight for resident protections","routeB":"support the expansion for jobs and compensation","finale":"secure a binding community agreement","unlock":"community housing, neighborhood jobs, and resident trust","category":"town","tags":["community","housing","labor"]},
  {"id":"spotlight-hills-property","name":"Spotlight Hills Property","districtId":"spotlight-hills","leadNpcId":"nico-valentine","leadNpcName":"Nico Valentine","leadRole":"luxury property manager","personality":"polished-anxious","premise":"Premium homes bring security, upkeep, image, private studios, neighbors, and the question of whether status is worth isolation.","skill":"property management","coreTask":"service and inspect hillside homes","complication":"a famous owner wants a worker blamed for property damage","routeA":"protect the worker and risk the client","routeB":"accept the cover story for elite access","finale":"manage a hillside emergency during a premiere","unlock":"premium home ownership and property contracts","category":"career","tags":["property","status","ethics"]},
  {"id":"independent-studio","name":"Independent Studio","districtId":"production-edge","leadNpcId":"imani-create","leadNpcName":"Imani Create","leadRole":"independent filmmaker","personality":"inventive-stubborn","premise":"The player can build a small production company through scripts, budgets, casting, equipment, permits, and distribution.","skill":"creative business","coreTask":"produce short projects and build a crew","complication":"a distributor offers reach but demands changing the story beyond recognition","routeA":"self-release the original work","routeB":"accept the changes and broader audience","finale":"premiere the completed independent project","unlock":"studio ownership and creator contracts","category":"career","tags":["business","film","ownership"]}
],
  supportNpcs: [
  {"id":"renee-lights","name":"Renee Lights","districtId":"backlot-commons","role":"lighting technician","personality":"dry-creative","goal":"get crew credit on screen","fear":"being invisible forever","secret":"keeps a reel of shots saved by technicians","value":"craft","petPeeve":"actors touching hot lamps"},
  {"id":"jojo-thread","name":"Jojo Thread","districtId":"glam-quarter","role":"costume tailor","personality":"warm-blunt","goal":"build clothes that move and last","fear":"fast fashion ruining the shop","secret":"sews names into repaired costumes","value":"craftsmanship","petPeeve":"people calling a safety pin tailoring"}
],
});

export default STARLINE_CITY_STORY_PACK;
