import { makeStoryPack } from '../storyFactory.js';

export const TECH_CITY_STORY_PACK = makeStoryPack({
  townId: "tech-city",
  label: "TechTown",
  baseMoney: 550,
  arcs: [
  {"id":"gridlink-mobility-network","name":"GridLink Mobility Network","districtId":"neon-core","leadNpcId":"priya-shah","leadNpcName":"Priya Shah","leadRole":"systems founder","personality":"fast-optimistic","premise":"The GridLink chain grows from personal teleportation into a citywide network with safety tests, outages, access rules, and public trust.","skill":"systems engineering","coreTask":"repair nodes and certify destinations","complication":"private investors demand paywalled emergency access","routeA":"protect public emergency use","routeB":"accept premium access tiers for faster expansion","finale":"stabilize the network during a cascading failure","unlock":"GridLink engineering contracts and advanced casing upgrades","category":"story","tags":["gridlink","technology","travel"],"homeTownId":"tech-city"},
  {"id":"codenest-startup-life","name":"CodeNest Startup Life","districtId":"neon-core","leadNpcId":"marcus-chen","leadNpcName":"Marcus Chen","leadRole":"startup founder","personality":"brilliant-scattered","premise":"The player joins a small startup through coding contracts, customer testing, funding pitches, cofounder conflict, and launch day.","skill":"coding and product design","coreTask":"debug features and interview users","complication":"an investor wants the team to sell private user data","routeA":"refuse and build a slower ethical business","routeB":"accept the deal and gain rapid growth with trust costs","finale":"launch the product during Tech Expo","unlock":"startup ownership and freelance contracts","category":"career","tags":["coding","business","privacy"]},
  {"id":"drone-district-flightpath","name":"Drone District Flightpath","districtId":"innovation-strip","leadNpcId":"zoe-rivera","leadNpcName":"Zoe Rivera","leadRole":"drone instructor","personality":"playful-precise","premise":"Drone training covers racing, delivery, photography, rescue, restricted airspace, and hardware maintenance.","skill":"drone control","coreTask":"complete flight courses and delivery routes","complication":"a competitor uses hacked navigation to sabotage races","routeA":"expose the cheat and rerun fairly","routeB":"use the hack to counter-sabotage","finale":"win the city aerial circuit and complete a rescue flight","unlock":"advanced drone licenses and daily routes","category":"activities","tags":["drones","racing","rescue"]},
  {"id":"cybercore-security-division","name":"CyberCore Security Division","districtId":"neon-core","leadNpcId":"nadia-cole","leadNpcName":"Nadia Cole","leadRole":"cybersecurity lead","personality":"cool-methodical","premise":"The player learns legal cybersecurity through monitoring, incident response, access control, and the danger of becoming the threat.","skill":"cybersecurity","coreTask":"trace attacks and secure systems","complication":"the breach began as an internal whistleblower operation","routeA":"protect the whistleblower while stopping collateral damage","routeB":"hand them over and preserve corporate trust","finale":"defend TechTown during a coordinated network attack","unlock":"security career and restricted system clearance","category":"career","tags":["cybersecurity","ethics","corporate"]},
  {"id":"voltbyte-robotics-league","name":"VoltByte Robotics League","districtId":"tech-campus","leadNpcId":"professor-eli-nash","leadNpcName":"Professor Eli Nash","leadRole":"robotics teacher","personality":"enthusiastic-exacting","premise":"Students build service robots, compete in challenges, and argue over whether winning matters more than useful design.","skill":"robotics and teamwork","coreTask":"design, repair, and program robots","complication":"a sponsor pressures the team to copy a rival's design","routeA":"build an original community-service robot","routeB":"copy the design and chase the trophy","finale":"complete the robotics finals during a real emergency","unlock":"robotics certification and custom helper projects","category":"career","tags":["school","robotics","competition"]},
  {"id":"gadget-forge-underlayer","name":"Gadget Forge Underlayer","districtId":"innovation-strip","leadNpcId":"jax-byte","leadNpcName":"Jax Byte","leadRole":"gadget technician","personality":"cool-skeptical","premise":"Behind legal repairs is a market for modified scanners, stolen charge cells, access chips, and devices with questionable histories.","skill":"repair and appraisal","coreTask":"fix devices and verify ownership","complication":"a device contains evidence of a larger theft network","routeA":"turn it in and protect customers","routeB":"sell access to the evidence and join the underlayer","finale":"shut down or seize control of the hidden exchange","unlock":"legal repair mastery or black-market gadget network","category":"people","tags":["gadgets","crime","investigation"]},
  {"id":"neon-drift-motors","name":"Neon Drift Motors","districtId":"innovation-strip","leadNpcId":"devon-pike","leadNpcName":"Devon Pike","leadRole":"vehicle engineer","personality":"competitive-restless","premise":"Electric and hover vehicle culture brings test tracks, customization, charging strategy, racing, and safety regulation.","skill":"vehicle engineering","coreTask":"tune vehicles and complete controlled trials","complication":"a prototype is fast but dangerously unstable","routeA":"delay launch and redesign it","routeB":"race it before regulators can stop the event","finale":"win the Neon Drift showcase without endangering the crowd","unlock":"tech vehicle ownership and custom tuning","category":"career","tags":["vehicles","racing","engineering"]},
  {"id":"server-relay-blackout","name":"Server Relay Blackout","districtId":"utility-edge","leadNpcId":"aiden-brooks","leadNpcName":"Aiden Brooks","leadRole":"infrastructure engineer","personality":"quiet-determined","premise":"A failing server relay threatens transit, clinics, housing, and police systems while corporate teams argue over blame.","skill":"infrastructure","coreTask":"maintain relays and route backup power","complication":"evidence suggests the failures were allowed to continue to justify privatization","routeA":"expose the scheme and keep services public","routeB":"help the takeover and gain corporate access","finale":"restore the city during a total blackout","unlock":"infrastructure career and emergency system control","category":"story","tags":["infrastructure","mystery","politics"]},
  {"id":"synapse-clinic-bioethics","name":"Synapse Clinic Bioethics","districtId":"neon-core","leadNpcId":"dr-samira-lee","leadNpcName":"Dr. Samira Lee","leadRole":"clinic researcher","personality":"compassionate-analytical","premise":"The clinic tests wearable health technology, recovery tools, accessibility devices, and the limits of data collection.","skill":"health technology","coreTask":"assist trials and help patients","complication":"a successful device stores private health data without proper consent","routeA":"halt the rollout and rebuild consent","routeB":"release it early to secure funding","finale":"save patients during a city systems outage","unlock":"clinic technology career and accessibility projects","category":"career","tags":["health","technology","privacy"]},
  {"id":"smart-city-who-watches","name":"Smart City: Who Watches?","districtId":"neon-core","leadNpcId":"councilor-isaiah-ward","leadNpcName":"Councilor Isaiah Ward","leadRole":"city technology councilor","personality":"measured-political","premise":"Cameras, sensors, predictive patrols, and automated services force the player to decide how much control a safe city should accept.","skill":"civic technology","coreTask":"audit systems and interview residents","complication":"a pilot system unfairly targets specific districts","routeA":"shut it down and rebuild transparent rules","routeB":"keep it running for higher security efficiency","finale":"lead the public vote and implement the chosen model","unlock":"civic tech influence and townwide state changes","category":"story","tags":["surveillance","politics","ethics"]}
],
  supportNpcs: [
  {"id":"mina-code","name":"Mina Code","districtId":"tech-campus","role":"student club captain","personality":"fast-curious","goal":"win without copying anyone","fear":"letting her team down","secret":"keeps an offline notebook because cloud sync betrayed her once","value":"originality","petPeeve":"passwords taped to monitors"},
  {"id":"ray-volt","name":"Ray Volt","districtId":"utility-edge","role":"power technician","personality":"blunt-calm","goal":"keep the grid boring and stable","fear":"a cascading blackout","secret":"can hear a bad relay before the monitors catch it","value":"competence","petPeeve":"people calling infrastructure magic"}
],
});

export default TECH_CITY_STORY_PACK;
