import { makeStoryPack } from '../storyFactory.js';

export const WORLD_STORY_PACK = makeStoryPack({
  townId: "world",
  label: "Cross-Town / World",
  baseMoney: 1000,
  arcs: [
  {"id":"crownwater-courier-network","name":"Crownwater Courier Network","districtId":"world-routes","leadNpcId":"alexis-route","leadNpcName":"Alexis Route","leadRole":"intertown courier chief","personality":"fast-resourceful","premise":"A world courier route links roads, boats, transit, GridLink, weather, fragile cargo, and town-specific laws.","skill":"logistics","coreTask":"complete deliveries across every town","complication":"a client asks the player to conceal illegal cargo among relief supplies","routeA":"protect the relief network","routeB":"take the smuggling contract","finale":"complete the longest timed delivery circuit","unlock":"world courier career and route bonuses","category":"career","tags":["world","delivery","travel"],"gate":"open-roads"},
  {"id":"academy-exchange-year","name":"Academy Exchange Year","districtId":"world-schools","leadNpcId":"dr-ava-cross","leadNpcName":"Dr. Ava Cross","leadRole":"exchange director","personality":"organized-curious","premise":"The player attends classes and projects in every specialized academy, building a personalized education path.","skill":"multidisciplinary learning","coreTask":"complete exchange projects","complication":"schools compete to claim the player's final project","routeA":"publish it as a shared city resource","routeB":"grant exclusivity to the highest-status school","finale":"present the World Academy Expo","unlock":"master certifications and tutor contracts","category":"career","tags":["world","school","skills"],"gate":"school-intro"},
  {"id":"intertown-justice-compact","name":"Intertown Justice Compact","districtId":"world-civic","leadNpcId":"judge-malcolm-fair","leadNpcName":"Judge Malcolm Fair","leadRole":"circuit judge","personality":"stern-humane","premise":"Different towns handle law, records, security, permits, and reform differently. The player helps build a fair cross-town framework.","skill":"law and policy","coreTask":"review cases across towns","complication":"a town tries to hide misconduct behind local jurisdiction","routeA":"force transparent standards","routeB":"accept local control for political support","finale":"ratify the Justice Compact","unlock":"record appeals, reform paths, and intertown law missions","category":"story","tags":["world","law","reform"],"gate":"police-orientation"},
  {"id":"zaylins-festival-circuit","name":"Zaylins Festival Circuit","districtId":"world-events","leadNpcId":"marisol-day","leadNpcName":"Marisol Day","leadRole":"festival producer","personality":"joyful-demanding","premise":"A season of town festivals creates a long logistics, performance, food, transit, safety, and reputation route.","skill":"event production","coreTask":"deliver one signature festival per town","complication":"sponsors demand every town use the same commercial format","routeA":"protect local identity","routeB":"standardize for maximum funding","finale":"produce the final Zaylins World Fair","unlock":"seasonal events and festival cosmetics","category":"story","tags":["world","festival","culture"],"gate":"arrival-casino-strip"},
  {"id":"business-without-borders","name":"Business Without Borders","districtId":"world-commerce","leadNpcId":"ronnie-enterprise","leadNpcName":"Ronnie Enterprise","leadRole":"business mentor","personality":"strategic-warm","premise":"The player connects shops, services, property, transport, entertainment, and technology into a multi-town business.","skill":"entrepreneurship","coreTask":"build partnerships and manage contracts","complication":"one expansion depends on underpaying a vulnerable town","routeA":"grow slower with fair standards","routeB":"take the cheap expansion and manage reputation damage","finale":"launch a world-spanning brand","unlock":"business ownership and passive contract systems","category":"career","tags":["world","business","ownership"],"gate":"first-job"},
  {"id":"crownwater-environmental-crisis","name":"Crownwater Environmental Crisis","districtId":"crownwater-basin","leadNpcId":"dr-kenya-earth","leadNpcName":"Dr. Kenya Earth","leadRole":"environmental coordinator","personality":"urgent-grounded","premise":"A basin-wide pollution and current crisis affects the harbor, Rich Hills, Casino bridge, Aqualume, wildlife, tourism, and jobs.","skill":"environmental response","coreTask":"trace sources and coordinate towns","complication":"multiple industries offer partial fixes that protect themselves","routeA":"force shared responsibility","routeB":"accept the fastest single-company solution","finale":"restore the basin through a world event","unlock":"environmental events and permanent water-state improvements","category":"story","tags":["world","environment","crisis"],"gate":"something-changed"},
  {"id":"starline-world-tour","name":"Starline World Tour","districtId":"world-stages","leadNpcId":"lana-starr","leadNpcName":"Lana Starr","leadRole":"talent agent","personality":"cool-demanding","premise":"A performance tour uses every town's venues, local culture, travel systems, crews, and public reputation.","skill":"performance logistics","coreTask":"book and perform across the world","complication":"management wants to erase local collaborators from the credits","routeA":"share credit and revenue","routeB":"centralize the brand around the player","finale":"complete the final Aqualume performance","unlock":"world fame and touring repeatables","category":"career","tags":["world","fame","performance"],"gate":"arrival-starline-city","homeTownId":"starline-city"},
  {"id":"gridlink-cascade","name":"GridLink Cascade","districtId":"gridlink-network","leadNpcId":"priya-shah","leadNpcName":"Priya Shah","leadRole":"systems founder","personality":"fast-optimistic","premise":"Every synchronized node begins misrouting travelers and cargo in a coordinated world-scale systems crisis.","skill":"network crisis response","coreTask":"diagnose failures in every town","complication":"the safest fix would permanently limit private teleport freedom","routeA":"accept transparent safety limits","routeB":"preserve full freedom with higher ongoing risk","finale":"restore the world network and expose the attacker","unlock":"advanced GridLink control and emergency travel","category":"story","tags":["world","gridlink","crisis"],"gate":"now-you-see-me","homeTownId":"tech-city"},
  {"id":"homes-across-zaylins","name":"Homes Across Zaylins","districtId":"world-properties","leadNpcId":"celeste-crown","leadNpcName":"Celeste Crown","leadRole":"property broker","personality":"polished-candid","premise":"The player experiences housing in every town, from apartments and cabins to yachts, studios, and underwater homes.","skill":"property management","coreTask":"inspect and maintain homes across towns","complication":"a speculative buying wave pushes residents out","routeA":"support resident-first ownership rules","routeB":"profit from the market and accept community costs","finale":"complete a world housing summit","unlock":"multi-home ownership and property management repeatables","category":"career","tags":["world","property","housing"],"gate":"property-desk-introduction","homeTownId":"rich-hills"},
  {"id":"make-your-mark-legacy","name":"Make Your Mark: Legacy","districtId":"world","leadNpcId":"zaylin-echo","leadNpcName":"Zaylin Echo","leadRole":"world chronicler","personality":"reflective-playful","premise":"The final authored spine does not end the sandbox. It reviews the player's relationships, careers, records, homes, choices, and impact, then opens a personalized legacy season.","skill":"reflection and world standing","coreTask":"resolve unfinished promises and gather witnesses","complication":"the player may rewrite the public story to hide painful choices","routeA":"show the honest history","routeB":"publish the polished legend","finale":"present the player's Story So Far and choose a legacy focus","unlock":"legacy titles, world contracts, and endless post-story play","category":"story","tags":["world","endgame","identity"],"gate":"make-your-mark"}
],
  supportNpcs: [
  {"id":"mason-mile","name":"Mason Mile","districtId":"world-routes","role":"road engineer","personality":"steady-practical","goal":"connect towns without flattening them","fear":"a route that harms a community","secret":"keeps old road signs in his garage","value":"access","petPeeve":"shortcuts that become somebody else's problem"},
  {"id":"alicia-booker","name":"Alicia Booker","districtId":"world-schools","role":"librarian","personality":"warm-precise","goal":"share knowledge across academies","fear":"paywalled education","secret":"maintains a banned-ideas shelf that is actually just difficult books","value":"learning","petPeeve":"folded page corners"},
  {"id":"frankie-ledger","name":"Frankie Ledger","districtId":"world-commerce","role":"accountant","personality":"deadpan-helpful","goal":"make businesses understand their own numbers","fear":"a client hiding losses","secret":"can spot a fake expense from three pages away","value":"clarity","petPeeve":"receipts photographed at unreadable angles"},
  {"id":"carmen-peace","name":"Carmen Peace","districtId":"world-civic","role":"mediator","personality":"calm-stubborn","goal":"keep conflict from becoming permanent","fear":"being used as a decoration","secret":"records agreements in plain language","value":"fairness","petPeeve":"apologies with the word 'if'"},
  {"id":"andre-clean","name":"Andre Clean","districtId":"crownwater-basin","role":"cleanup captain","personality":"cheerful-serious","goal":"make environmental work visible","fear":"people getting tired before the job is done","secret":"knows where every town's trash actually ends up","value":"responsibility","petPeeve":"ceremonial cleanups with no disposal plan"},
  {"id":"zoe-calendar","name":"Zoe Calendar","districtId":"world-events","role":"scheduler","personality":"hyper-organized","goal":"prevent every major event from happening on the same day","fear":"one impossible double booking","secret":"sleeps with a clipboard nearby","value":"coordination","petPeeve":"people saying 'just squeeze it in'"}
],
});

export default WORLD_STORY_PACK;
